week1/BOJ_2548/대표자연수_홍지훈.js, week1/BOJ_2548/대표자연수_홍지훈.py
- 백준 2548-대표 자연수
`brute-force`, `sort`
`js`
- 입력을 받기 위해 fs 대신 readline 사용
- 결과를 출력할 result 와 매번 합계를 구할 smallestSum 변수 생성
- time complexity : O (n^2)
- 주어진 조건 `1. 차이가 최소로 하는 자연수, 2.차이가 같을때 더 작은 수` 을 만족하는 result
`python`
- 정렬 후 중간값 찾기
- N 이 짝수일 때 N // 2 - 1, N 이 홀수일 때 N // 2 를 인덱스로 갖는 배열의 값이 차이가 최소가 되는 자연수
=> [BOJ] 2548_대표자연수 / 실버3 / 30분 / O

week1/BOJ_11399/ATM_홍지훈.js, week1/BOJ_11399/ATM_홍지훈.py
- 백준 11399-ATM
`정렬`
앞에서부터 반복문을 돌릴때 앞의 숫자가 뒤의 숫자보다 더 많이 더해지니 오름차순으로 정렬후 수를 더해야 한다.
이때 js 의 경우 `Array.prototype.sort()` 는 정렬시 먼저 문자열로 변환한 뒤 UTF-16 의 값을 기준으로 비교하여 정렬하므로 의도한 것처럼 숫자 크기순으로 정렬이 되지 않는다. 만약 숫자의 크기대로 정렬을 하고 싶으면 sort 의 인자로 비교함수를 전달해야 한다.
이때 콜백함수로 전달되는 비교함수는 리턴값이 숫자여야 하며 음수일 경우 첫번째 파라미터 a 가 두번째 파라미터 b 보다 작은 것이고 양수일 경우 그 반대이다.
```js
const compareFunc = function (a, b) {
return a - b
}
```
> 위의 코드는 오름차순 정렬이다.
=> [BOJ] 11399_ATM / 실버4 / 10분 / O

week1/BOJ_18114/블랙프라이데이_홍지훈.py
- 백준 18114-블랙프라이데이
`list sort()` => TimSort ( Merge Sort + Insert Sort )
- 시간복잡도 O(nlogn) 소요
- 최소 O(n) 최악 O(nlogn)
`bisect.bisect_left(list, target)`
- 이진탐색 O(logn)
- 특정 리스트 내에 타겟이 존재하는지 이진탐색으로 확인후 존재한다면 해당 인덱스 반환
- 존재하지 않는다면 정렬 순서에 맞는 인덱스에 삽입후 해당 인덱스 반환
- 리스트는 정렬이 되어있어야 한다
1. 총 무게합에 해당하는 무게가 1개 / 2개 / 3개의 합일때 3가지 경우로 나눠서 생각한다
2. 총 무게를 C, 입력받은 무게들의 리스트를 nums 라고 하며 nums 는 list.sort() 로 오름차순 정렬시킨다.
3. nums 에 대해 bisect 의 `bisect.bisect_left` 를 import 받아 사용한다.
4. 1) 1개일 경우 `bisect.bisect_left(nums, C)` 가 N 보다 작다면 nums 내에 C 가 존재하는지 여부를 이진탐색으로 확인한다. x in list 는 O(n) 으로 이진탐색의 성능이 더 좋다.
5. 2) 2개, 3개일 경우 투포인터 접근 방식을 적용한다. 정렬된 리스트 nums 의 끝과 끝을 작은 쪽 index = 0 을 i, 큰 쪽 index = N - 1 을 j 로 둔다. j 가 i 보다 클때 while 문으로 반복문을 돌릴때 만약 nums[i] + nums[j] 가 C 보다 크다면 너무 큰 수를 더하고 있으니 큰쪽 j 의 인덱스를 1 감소, 반대로 nums[i] …
=> [BOJ] 18114_블랙프라이데이 / 골드5 / 2시간 / X

week1/BOJ_1251/단어나누기_홍지훈.py
- 백준 1251-단어나누기
`sort`, `brute-force`
- brute-force 이니 이중 반복문을 그냥 써도 상관 없겠다는 생각이 들었습니다
- 두번째 단어, 세번째 단어가 시작하는 인덱스를 i, j 로 두고 단어를 3개의 단어로 나눈 뒤, 배열에 `append()` ( `O(1)` ) 하고 오름차순 정렬 `arr.sort()` ( `O(nlogn)` ) 하여 가장 앞에 있는 단어를 출력했습니다
=> [BOJ] 1251_단어나누기 / 실버5 / 40분 / O

week1/BOJ_11399/ATM_배정은.py, week1/BOJ_1251/단어 나누기_배정은.py
- 백준 1251번 - 단어나누기
`brute-force`
- 세 가지의 단어로 나눌 수 있는 모든 경우의 수를 탐색해본다. (완전 탐색)
- 뒤집은 방법은 문자열 슬라이싱(**list[::-1]**)을 통해  뒤집는다.
> 만약 `apple`이라는 단어라면,
`a`, `p`, `ple` | `a`, `pp`, `le` | `a`, `ppl`, `e` => 이런식으로 두 개의 지점을 기준으로 나눌 수 있다.
=> [BOJ] 1251_단어나누기 / 실버5 / 30분 / O

week1/BOJ_1931/회의실배정_홍지훈.py
- 백준 1931-회의실배정
- `그리디 알고리즘`, `정렬`
- 회의를 가장 많이 하려면 끝나는 시간 기준으로 먼저 정렬한 뒤, 시작하는 시간 기준으로 정렬해야 한다. 이때 lamda 함수를 이용하여 정렬할 수 있다.
- 만약 현재 시작시간이 이전 끝나는 시간보다 크거나 같다면 회의를 할 수 있으니 count 를 증가시킨다.
> 그리디 알고리즘은 현재 상황에서 지금 당장 좋은 것만 고르는 알고리즘이니 보통 정렬과 같이 출제되며 이 문제에선 끝나는 시간을 기준으로 풀이를 해야 했다..
- sort 함수의 인자중 key 로 lambda 함수를 넘겨줄때, labmda 함수에 여러 인자를 전달시 차례대로 정렬한다.
```py
list.sort(key = lambda x: (x[1], x[0]))
```
- list 가 `[[1, 3], [3, 13] ... ]` 같은 구조로 되어있을때 각 인덱스에 속하는 배열의 1번 인덱스를 기준으로 오름차순 정렬한뒤 0번 인덱스를 기준으로 다시 오름차순 정렬한다.
=> [BOJ] 1931_회의실배정 / 실버1 / 2시간 / X

week1/BOJ_1449/수리공항승_홍지훈.py
- 백준 1449-수리공항승
- `그리디 알고리즘`,  `정렬`
- 그리디 알고리즘인 만큼 정렬과 같이 출제가 되었다는 점을 생각했습니다
- 정렬된 값들을 탐색할 때 이전 값으로부터 L - 1 더한 값까지는 테이프가 추가로 필요하지 않고 그 이상의 경우 테이프가 추가되어야 한다는 점을 고려했습니다
=> [BOJ] 1449_수리공항승 / 실버3 / 40분 / O

week1/BOJ_1931/회의실배정_배정은.py
- 백준 1931-회의실배정
`brute-force`, `sort`
1. `끝나는 시간`을 기준으로 **오름차순 정렬** → 끝나는 시간이 같을 경우 : `시작 시간`이 이른 순으로 정렬
2. 첫 번째 회의 시간만 check ! 
- Python에서 `sort` 또는 `sorted`문법을 통해 정렬을 많이 하는데, **원하는 값을 기준으로 정렬을 하고 싶을 때는 `key`의 인자 값을 변경**해야 한다.
```python
meets = sorted(meets, key = lambda x : (x[1], x[0])) 
```
- 해당 코드는 1번째 인덱스로 먼저 정렬한 뒤 같으면 0 번째 인덱스 기준으로 정렬한다.
>  처음엔 다 확인 했는데.. 시간초과가 너무 나서 생각해보니 첫 번째 회의 시간만 체크하면 된다는 것을 알게 되었습니다😊
❗ **불필요한 반복문**은 사용하지 말자❗
=> [BOJ] 1931_회의실배정 / 실버1 / 40분 / O

week1/BOJ_1449/수리공항승_배정은.py
- 백준 1449-수리공항승
`brute-force`, `sort`
1. 입력받은 물의 위치를 **오름차순으로 정렬**
2. `다음 인덱스의 물 위치 - 현재 인덱스의 물 위치 < 테이프의 길이` 조건이 성립될 경우 가리키고 있는 인덱스를 `다음 인덱스`로 업데이트
2-1. 조건이 성립되지 않을 경우, 현재 인덱스 위치를 반환
```python
if water_position[idx] - water_position[position] < L:
next_position = idx
else:
return next_position, count + 1
```
- 위와 같은 코드의 형식으로 **완전 탐색** 방법으로 접근❗
=> [BOJ] 1449_수리공항승 / 실버3 / 20분 / O

week1/BOJ_18114/블랙프라이데이_배정은.py
- 백준 18114-블랙프라이데이
`brute-force`, `sort`
**시간복잡도**를 고려하여 **dictionary** 자료형을 통해 접근❗
- 우선, 무게를 **오름차순으로 정렬**한다.
- 이때, **무게가 C보다 큰 것**은 저장하지 않는다. 
- 총 세가지의 경우의 수를 생각하여 모두 탐색한다.
- **1개의 물건**의 무게 합이 충족할 경우
- **2개의 물건**의 무게 합이 충족할 경우 
- **3개의 물건**의 무게 합이 충족할 경우
**※ 이렇게 세 가지의 조건을 통해 하나만 충족할 경우 바로 결과를 반환하는 방식으로 문제를 풀었다.**
> `시간초과`와 `틀렸습니다`의 반복으로.... 2시간동안 최대한 여러 가지 방법을 적용하여 시간복잡도를 줄여보려고 했습니다...❗
> 혹시 파이썬을 쓰시는 분들은 최대한 dictionary의 연산이 **O(1)**인 것을 활용하여 문제를 푸시는 것을 추천합니다😊
> - List의 `in`, `index`와 같은 연산은 시간 복잡도가 **O(n)**이니 참고하여 푸시길 바라겠습니다!
=> [BOJ] 18114_블랙프라이데이 / 골드5 / 2시간 / O

week1/BOJ_2470/두용액_배정은.py
- 백준 2470번-두 용액
`brute-force`, `sort`, `two-pointer`
- 두 용액의 합의 **절댓값을 기준**으로 0과 가까운지를 보았고 0과 가까운 두 용액의 합과 해당 위치의 용액을 기억
- `투 포인터` 알고리즘 방식으로 접근
- **두 용액의 합이 0 보다 작으면 왼쪽 인덱스를 가르키는 포인터를 증가**
- **크면 두 수의 합이 더 작아야하므로 오른쪽 인덱스를 가르키는 포인터를 증가**
> 드디어 시간초과가 나지않고 풀었습니다😊
=> [BOJ] 2470_두용액 / 골드5 / 2시간 / X

week2/BOJ_10828/10828_스택_조재은.py
10828 스택
구현, 자료구조, 스택
간단하게 list를 만들어, list 요소를 기준으로 if 문을 통해 작성하였습니다.
=> [BOJ] 10828_스택 / 실버4 / 30분 / O

week2/BOJ_10828/스택_홍지훈.py
- 백준 10828-스택
`구현`, `자료구조`, `스택`
스택으로도, 큐로도 구현하기 용이한 collections 라이브러리의 deque 로 스택을 구현했습니다.
python 으로 클래스를 자주 안써봤더니 시간이 좀 걸렸네요..
> 추가로 switch 문을 사용하고자 match 를 쓰려는데 3.10.xx 버전인데 문법 오류가 떠서 if 문으로 대체했습니다.. 왜 안되었을지 찾아보는 중입니다.
=> [BOJ] 10828_스택 / 실버4 / 40분 / O

week2/BOJ_9012/괄호_홍지훈.py
- 백준 9012-괄호
`스택`
- `(` 는 stack 에 append
- `)` 는 stack 이 비어있지 않다면 마지막에 들어온 요소를 `pop` 
`stack 의 LIFO`
- 만약 stack 이 비어있었다면 반복문을 종료한다.
- 스택이 비었고 유효하다면 `YES` 를 출력하고 그렇지 않은 경우 `NO` 를 출력한다.
> 문자열의 길이가 2~50 이므로 문자열을 `brute force` 방식 으로 for 문을 돌려도 큰 문제가 없을 것 같다는 생각을 하며 풀었습니다.
=> [BOJ] 9012_괄호 / 실버4 / 40분 / O

week2/BOJ_10828/스택_배정은.py
- 백준 10828번-스택
`stack`
- Python에 있는 `list` 자료형의 **기본 내장 함수**를 통해 구현
- push 기능은 `list.append()` 함수 사용
- pop 기능은 `list.pop()` 함수 사용
=> [BOJ] 10828_스택 / 실버4 / 5분 / O

week2/BOJ_9012/괄호_배정은.py
- 백준 9012번-괄호
`stack`
- 문자열의 길이가 `2이상 50이하`이므로 for문을 통해 순차적으로 탐색하여 **스택**에 입력
- 스택에서 **값을 추출**하는 조건 : **stack의 top이 `(` 이고 현재 문자가 `)`일 경우**
- 스택에서 **값을 넣는** 조건 : **stack의 길이가 0이거나 위와 같은 조건이 아닐 경우**
=> [BOJ] 9012_괄호 / 실버4 / 10분 / O

week2/BOJ_2346/풍선터뜨리기_홍지훈.py
- 백준 2346-풍선터뜨리기
`덱`
- 터뜨리는 풍선의 번호는 `인덱스 + 1` 이다.
- 입력받은 숫자들의 리스트를 enumerate 를 통해 엔트리 형태로 덱에 저장한다.
- 입력받은 숫자만큼 `for 문` 을 돌때 인덱스를 출력할 리스트에 `append` 한다.
- 이때 deq 이 남아있을때 엔트리에 저장된 값이 양수, 음수인지에 따라 마지막 값을 처음으로 저장하거나 첫 번째 값을 마지막에 저장하는 식으로 위치를 변경시킨다.
=> [BOJ] 2346_풍선터뜨리기 / 실버3 / 20분 / O

week2/BOJ_10799/쇠막대기_홍지훈.py
- 백준 10799-쇠막대기
`스택`
> 처음에 덱으로 풀이하려다가 관련 알고리즘에 스택이 있어 스택으로 풀이를 진행했습니다.
`stack 이용`
- ) 가 pop 되면 ) 수 카운트
- ( 가 pop 되고 바로 이전값이 ) 였다면 ) 수 1 감소하고 그때까지 나온 ) 수만큼 result 에 카운트
- ( 가 pop 되고 바로 이전값이 ( 였다면 result 에 1 카운트하고 ) 수 1 감소
=> [BOJ] 10799_쇠막대기 / 실버2 / 40분 / O

week2/BOJ_2800/괄호제거_홍지훈.py
- 백준 2800-괄호제거
`스택`, `조합`, `문자열`
- 먼저 입력받은 문자열을 스택으로 전환합니다.
- 스택을 순회하면서 여는 괄호가 나오면 새로운 스택 `bracketStack` 에 여는 괄호의 인덱스를 append 하고
- 닫는 괄호가 나오면 `bracketStack` 에서 pop 해서 여는 괄호와 이와 쌍이 되는 `pair` 의 인덱스를 튜플 형태로 `pair` 라는 스택에 append 합니다.
여기까지 여는 괄호와 닫는 괄호의 쌍의 인덱스를 튜플로 구하는 로직입니다.
- 이후 `itertools` 의 `combinations` 를 사용하여 중복되지 않는 모든 경우의 수를 구해 각각의 pair 를 1개 이상 고를 경우 모든 경우를 구합니다.
```py
for i in range(len(pair)):
cases.append(list(combinations(pair, i + 1)))
```
- 각각의 경우 여는 괄호와 닫는 괄호를 '' 빈 문자열 처리해준 결과를 answer 에 add 하고 출력합니다.
=> [BOJ] 2800_괄호제거 / 골드5 / 120분 / X

week2/BOJ_9012/9012_괄호_조재은.py
9012 - 괄호
stack
'(' 괄호가 들어오면 stack에 넣어준다.
')' 괄호가 들어왔을 때는 stack을 검사해 비어 있다면 NO 를 출력 후 break해주고 만약 비어있지 않다면 pop을 한번 해준다.
=> [BOJ] 9012_괄호 / 실버4 / 30분 / O

week2/BOJ_1966/프린터큐_배정은.py
- 백준 1966번-프린터 큐
`queue`, `brute-force`
- 가장 앞에 있는 중요도를 기준으로 다음 인덱스 (`idx + 1`)  부터 마지막 인덱스까지의 리스트에서 큰 값이 있을 경우에 `pop`연산을 진행한 뒤 맨 뒤에 `push`연산을 진행
- **pop 연산** : `popleft()`, **push 연산** : `append()`
> 설명대로 정석적으로 접근하였습니다😊
파이썬에서 `deque`가 시간복잡도 측면에서 더 빠르게 `pop`연산을 진행하므로 해당 자료형을 사용하였습니다.
=> [BOJ] 1966_프린터큐 / 실버3 / 20분 / O

week2/BOJ_1966/프린터큐_조재은.py
1996 프린터큐
큐
q의 max값이 q의 0번째와 비교하고, temp라는 리스트를 만들어서 입력값 m번의 인덱스 값에만 1을 넣어 비교를 해보았습니다
=> [BOJ] 1996_프린터큐 / 실버3 / 60분 / O

week2/BOJ_2346/풍선터뜨리기_홍지훈.py
- 백준 2346-풍선터뜨리기
`덱`
기존 코드중 result 에 결과를 다시 저장할 필요없이 바로 출력하도록 수정하고
가독성을 위해 deq.rotate() 메서드 사용
=> [BOJ] 2346_풍선터뜨리기 / 실버3 / 20분 / O / 개선

week2/BOJ_2346/2346_풍선터뜨리기_조재은.py
2346 풍선터뜨리기
리스트
enumerate 이용하여 인덱스 번호활용
양수이면 오른쪽, 음수이면 왼쪽을 타게 코드 작성
=> [BOJ] 2346_풍선터뜨리기 / 실버3 / 60분 / X

week3/BOJ_20546/기적의매매법_홍지훈.py
- 백준 20546-기적의매매법
`구현`
`준현`
- 돈이 남으면 살수 있는 만큼 모두 매수
`성민`
- 3일 연속으로 주가가 상승, 하락하는 날 각각 매도, 매수
- 연속된 날을 count 하는 수치는 상승에서 하락, 하락에서 상승으로 꺾이거나 주가가 동일하게 되는 경우에만 리셋
- 매도는 주가가 있어야 가능한 것이라 매수를 한 뒤, 매도 가능
=> [BOJ] 20546_기적의매매법 / 실버5 / 30분 / O

week3/BOJ_4396/지뢰찾기_홍지훈.py
- 백준 4396-지뢰찾기
`구현`
- 폭탄 정보가 담긴 graph1 과, 현재까지 클릭한 정보가 담긴 graph2 를 생성합니다.
- 먼저 크기에 맞게 . 으로 이루어진 answer 행렬을 생성합니다.
- 각 셀을 돌며 graph1 의 셀과 graph2 의 셀을 비교하며 graph1 가 . 이고 graph2 가 x 라면 무사히 클릭한 것이라 인접한 지뢰의 수를 카운트합니다.
- graph1 가 * 이고 graph2 가 x 라면 폭탄을 클릭한 것이니 모든 셀을 돌며 graph1 에서 * 인 지점을 answer 의 같은 좌표에 * 을 기록합니다.
=> [BOJ] 4396_지뢰찾기 / 실버4 / 1시간 30분 / O

week3/BOJ_1913/달팽이_홍지훈.py
- 백준 1913-달팽이
`구현`
- 0 으로 채워진 N * N 크기의 answer 생성
- 이동거리가 반복되는 주기를 distance 에 생성
- 이동방향을 담은 direction 생성
- 각 셀별로 움직이는 이동방향을 결정하여 다음 인덱스를 구하고 1씩 카운트하여 answer 행렬을 업데이트
- N x N -> 2N - 1 회
- 3     -> 5
- 5     -> 9
- 7     -> 13
- 9     -> 17
- 이동거리
- 1 -> 1 -> 2 -> 2 -> (2)
- 1 -> 1 -> 2 -> 2 -> 3 -> 3 -> 4 -> 4 -> (4)
- 1 -> 1 -> 2 -> 2 -> 3 -> 3 -> 4 -> 4 -> 5 -> 5 -> 6 -> 6 -> (6)
- 1 -> 1 -> 2 -> 2 -> 3 -> 3 -> 4 -> 4 -> 5 -> 5 -> 6 -> 6 -> 7 -> 7 -> 8 -> 8 -> (8)
- 방향 인덱스 변화
- 0 -> 1 -> 2 -> 2 -> 3 -> 3 -> 0 -> 0
- 0 -> 1 -> 2 -> 2 -> 3 -> 3 -> 0 -> 0 -> 0 -> 1 -> 1 -> 1 -> 2 -> 2 -> 2 -> 2 -> 3 -> 3 -> 3 -> 3 -> 0 -> 0 -> 0 -> 0
> 시간복잡도를 어디서 줄일 수 있을지 감이 안잡히네요.. 너무 오래 걸리는 것 같아요
=> [BOJ] 1913_달팽이 / 실버3 / 70분 / O

week3/BOJ_15787/기차가어둠을헤치고은하수를_홍지훈.py
- 백준 15787-기차가어둠을헤치고은하수를
`구현`, `비트마스킹`
- a & b - and 연산
- a | b - or 연산
- a ^ b - xor 연산 (둘이 다르면 1, 아니면 0)
- ~a - not
- a << b - a 를 b 비트만큼 왼쪽으로 시프트 a = 001 b = 2 => a << b => 100
- a >> b - a 를 b 비트만큼 오른쪽으로 시프트
- {A, B, C, D, E} => {A} = 10000
- 현재 상태 cur 이 있을 때 p 번 원소 추가시 아래와 같은 코드는 p 번 left shift 를 한 뒤, or 연산을 하므로 내가 원하는 p 번째 자리를 1 로 바꿔서 원소를 추가하듯 동작할 수 있게 된다.
- cur = cur | (1 << p)
- & 는 둘다 1이어야 1이므로 특정 p 번째 비트만 0으로 만들어 p 번째 비트만 0으로 전환시켜줄 수 있는 방식이다.
- cur = cur & ~ (1 << p);
- ^ 는 다르면 1, 같으면 0인데 p 번째만 1이니 원래 p 번째가 1 이었다면 0으로 0 이었다면 1로 토글될 수 있다.
- cur = cur ^ ( 1 << p )
- a | b 합집합
- a & b 교집합
- a & ~b a 에서 b 를 뺀 차집합
- a ^ b a 와 b 중 하나에만 포함된 원소들의 집합
- 하나의 기차는 20개의 일렬로 된 좌석이 있다.
- 명령의 종류 4가지
- 1 i x : i 번째 기차 x 번째 좌석에 사람 태우기 => 이미 있다면 continue
- 2 i x : i 번째 기차 x 번째 앉은 사람은 하차 => 없었다면 …
=> [BOJ] 15787_기차가어둠을헤치고은하수를 / 실버2 / 100분 / O

week3/BOJ_16926/배열돌리기_홍지훈.py
- 백준 16926-배열돌리기
- `덱`, `구현`
- 행렬을 껍질별로 추출한다.
- 덱으로 껍질을 감싸고 deque.rotate() 로 회전시킨다.
- 회전한 껍질을 다시 행렬로 결합한다.
> 2시간을 훌쩍 넘어 고민고민하다가 결국 도저히 모르겠어서 다른 분들의 풀이를 참고했습니다.. ㅠㅠ 행렬 회전하면 90도 회전만 생각하다가 각 층별로 회전시키는 방법을 알아가네요
=> [BOJ] 16926_배열돌리기 / 실버1 / 120분 / X

week3/BOJ_16719/ZOAC_홍지훈.py
fail case
- 백준 16719-ZOAC
`재귀`
> 메모리 부족하다는 것 때문에 머리 터지는 줄 알았네요.. 사용된 메모리가 어떤지 성공하기 이전에도 알려주면 좋겠는데 방법이 없을까요..?
- 시작과 끝을 파라미터로 전달하는 함수를 하나 생성합니다.
- 입력한 문자열과 길이가 같은 크기의 False 로 채워진 배열 c 를 생성합니다.
- 해당 범위 내의 문자중 최소값과 해당 최소값의 인덱스를 찾고 해당 최소값은 방문했으니 c[idx] = True 로 변경합니다.
- 전체 문자열을 순회하며 전체 문자열중 방문한 문자들을 출력합니다.
- 이 과정을 오른쪽 범위 내에서 다시 반복하고 없다면 왼쪽 범위내에서 다시 반복합니다.
=> [BOJ] 16719_ZOAC / 골드5 / 120분 / X

week3/BOJ_15787/기차가 어둠을 헤치고 은하수를_조재은.py
15787 기차가 어둠을 헤치고 은하수를
구현
- 기차 각각을 원소 20개를 가진 리스트로 생성
- 은하수를 통과한 기차의 상태를 저장하는 리스트 state를 만들고,
- for문을 기차 수만큼 돌려서 i번째 기차의 상태가 state에 없다면 state에 삽입하고 cnt += 1
=> [BOJ] 15787_기차가 어둠을 헤치고 은하수를/ 실버1 / 120분 / X

week3/BOJ_1913/달팽이_조재은.py
1913 달팽이
구현
- 방향벡터 (상, 하, 좌, 우) 이용
- n*n의 시작 좌표 (중심점)
- 현재 좌표가 표를 다 돌아, (0,0)이 될 때까지, 번호가 현재 외각의 크기만큼 할당될 때까지
- 현재 좌표가 현재 외각의 시작 좌표라면, 상으로 이동, 상우하좌로 이동해야하는 횟수 저장
- 상으로 이동해야하는 횟수 감소, 현재 좌표에 번호 할당 후 n개의 줄에 걸쳐 표를 출력
=> [BOJ] 1913_달팽이 / 실버3 / 60분 / X

week3/BOJ_4396/지뢰찾기_조재은.py
=> [BOJ] 4396_지뢰찾기 / 실버4 / 120분 / X

week3/BOJ_20546/기적의매매법_조재은.py
=> [BOJ] 20546 기적의 매매법/ 실버5 / 60분 / X

week4/BOJ_2578/빙고_홍지훈.py
- 백준 2578-빙고
`구현`
- 철수의 빙고판과 사회자가 부르는 숫자를 각각 user, nums 스택에 저장합니다.
- 사회자의 숫자를 하나씩 읽으면서 해당 숫자에 해당하는 철수 빙고판의 인덱스를 토대로 철수 빙고판의 row, col 을 구합니다.
- row, col 은 dictionary 에 각각의 인덱스를 카운트하여 5가 될 경우 빙고 1을 충족한다고 판단합니다.
- 대각선은 2종류만 존재하니 row, col 이 같은 경우와 row + col == 4 일 경우 2가지가 빙고 1을 충족할 수 있습니다.
- 이 조건의 합이 3보다 크거나 같아지면 게임을 종료합니다. 이때까지의 인덱스를 통해 몇번째에 종료되었는지 확인합니다.
`itertools 의 chain.from_iterable`
> javascript 에서 flatMap 을 사용하듯이 iterable 의 요소를 꺼내는 메서드입니다. 인자에 리스트를 넣으면 요소들을 모두 꺼내줍니다.
```py
user = list(chain.from_iterable([list(map(int, input().split())) for _ in range(5)]))
```
- 5줄의 공백으로 구분된 숫자들로 구성된 행렬을 마치 spread 문법처럼 요소들을 끄집어내어 다시 하나의 스택에 담는 코드입니다.
=> [BOJ] 2578_빙고 / 실버4 / 60분 / O

week4/BOJ_20436/ZOAC3_홍지훈.py
- 백준 20436-ZOAC3
`구현`
- 그닥 케이스가 많지 않아서 그냥 모든 키보드의 좌표를 dictionary 에 저장해두고 왼쪽일때와 아닐때 각각 좌표를 업데이트시키며 최대치를 갱신해주었습니다.
> 최소한의 시간을 구하라 해서 순서도 중요한가? 하며 고민하다 시간이 많이 지나갔네요
심지어 맞는 코드 짜두고 print(total) 을 안하고 print('total : ', total) 이렇게 해서 한참동안 삽질했네요,ㅠㅠ
=> [BOJ] 20436_ZOAC3 / 실버4 / 50분 / O

week4/BOJ_12933/오리_홍지훈.py
- 백준 12933-오리
`구현`, `해시 테이블`, `그리디 알고리즘`
- 오리의 울음은 q 로만 시작할 수 있다. 
- q 는 기존 오리가 새로 울기 시작할 수 있고 새 오리가 울기 시작할 수 있다.
- 그 외의 문자열은 반드시 기존 오리의 울음 상태중 이어서 나올 위치가 존재해야 한다.
- 그런데 마지막의 울음 소리까지 나왔는데 `quack` 쌍이 완성되지 않은 오리가 존재한다면 불완전한 울음이 존재하는 경우다.
- 해시테이블을 만들어 키는 오리의 인덱스 (몇번째 오리인지), 값은 quack 의 인덱스를 의미한다. 그래서 문자열을 순회하면서 각 오리별 마지막까지 울었던 문자가 무엇인지 기록할 수 있다.
=> [BOJ] 12933_오리 / 실버3 / 110분 / O

week4/BOJ_22858/원상복구(small)_홍지훈.py
- 백준 22858-원상복구(small)
`구현`
- Si Di 가 갖는 인덱스는 동일합니다.
- 이전 Si 의 idx, val 를 구했을때 그 시점에서의 P 는 인덱스가 Di[idx] - 1 일때 val 입니다.
=> [BOJ] 22858_원상복구(small) / 실버3 / 30분 / O

week4/BOJ_2615/오목_홍지훈.py
- 백준 2615-오목
`구현`, `브루트 포스`
- 현재 위치를 기준으로 오목이 완성되었는지 확인할 수 있다.
- 오목의 가장 위 혹은 가장 왼쪽 좌표를 알아야 하므로 방향은 아래의 4가지 방향만 확인한다.
- 오른쪽 위 대각선 방향에 오목이 존재하는지 비교
- row >= 4 and col <= 14
- 오른쪽 방향에 //
- col <= 14
- 오른쪽 아래 방향에 //
- row <= 14 and col <= 14
- 아래 방향에 //
- row <= 14
- 육목 여부를 확인한다.
- 오목이어도 현재 방향의 다음 좌표의 값이 일치하는지 여부를 체크한다.
- 현재 방향 시작점의 이전 좌표가 존재한다면 시작점의 값과 이전 좌표의 값이 다른지 비교한다.    
- 현재 위치에서 현재 위치의 바둑알의 색깔과 오목이 존재할 때 현재 위치의 좌표를 출력한다.
- 한쪽이 이길 경우 바둑돌의 색을, 승부가 결정되지 않았으면 0 을 출력한다.
=> [BOJ] 2615_오목 / 실버1 / 110분 / O

week4/BOJ_14719/빗물_홍지훈.py
- 백준 14719-빗물
`구현`
- 빗물은 높은 H 사이에 고이게 됩니다.
- 시작부터 가장 높은 H 까지 빗물을 구하는 로직과 끝에서부터 가장 높은 H 까지 빗물을 구하는 로직이 같습니다.
- 그래서 가장 높은 지점을 기준으로 앞의 영역과 뒤의 영역을 분리하여 고인 빗물을 구합니다.
- 두가지 영역으로 나누었으나 빗물을 구하는 로직이 같습니다.
- 빗물을 총 빗물 양에 더하게 되는 시점은 높이가 0이 아니면서 이전까지 최대 높이와 비교시 현재의 높이가 그보다 같거나 클 때 입니다.
- 반면 현재의 높이가 이전까지의 최대 높이보다 작다면 해당 높이와 현재 높이의 차이만큼 현재 신점에 빗물이 추가로 고이게 됩니다.
=> [BOJ] 14719_빗물 / 골드5 / 20분 / O

week4/BOJ_21608/상어 초등학교_홍지훈.py
- 백준 21608-상어 초등학교
`구현`
> 골드5는 풀이하기 좀 어려워서 기능 명세서를 미리 생각해보고 코드를 짰습니다. 풀이는 가능하지만 너무 길어진 느낌이 드네요.. 구현이 가장 막막한거같아요ㅠㅠ
=> [BOJ] 21608_상어 초등학교 / 골드5 / 120분 / O

week4/빙고_배정은.py
- 백준 2578-빙고
`구현`, `brute-force`
- 빙고 맵을 저장할 수 있는 `2차원 배열`을 우선적으로 만든 뒤 해당 위치에 값을 제거하여 빙고 갯수를 계속 세는 방식으로 진행
=> [BOJ] 2578_빙고 / 실버4 / 30분 / O

week4/BOJ_14719/빗물_조재은.py
=> [BOJ] 14719_빗물 / 골드5 / 60분 / O

week4/BOJ_12933/오리_조재은.py
=> [BOJ] 12933_오리 / 실버3 / 80분 / O

week4/BOJ_2578/빙고_조재은.py
=> [BOJ] 2578_빙고 / 실버4 / 100분 / O

week4/BOJ_20436/zoac_조재은.py
=> [BOJ] 20436_zoac3 / 실버4 / 60분 / O

week4/BOJ_21608/상어초등학교_이동혁.py
- 백준 21608-상어 초등학교
구현
조건 들을 모두 함수로 선언:
1. 비어있는 칸 중에서 좋아하는 학생이 인접한 칸에 가장 많은 칸으로 자리를 정한다. -> find_seat_condition1()
조건에 맞는 자리의 인덱스를 모두 반환
2. 1을 만족하는 칸이 여러 개이면, 인접한 칸 중에서 비어있는 칸이 가장 많은 칸으로 자리를 정한다. -> find_seat_condition2()
조건에 맞는 자리의 인덱스를 모두 반환
3. 2를 만족하는 칸도 여러 개인 경우에는 행의 번호가 가장 작은 칸으로 -> find_seat_condition3()
조건에 맞는 자리의 인덱스를 모두 반환
4. 3번 조건에 맞는 칸도 여러 개이면 열의 번호가 가장 작은 칸으로 자리를 정한다. -> find_seat_condition4()
조건에 맞는 자리의 인덱스를 모두 반환
가장 첫번째로 오는 학생은 무조건 (2,2) 자리로 (인덱스로는 (1,1))
이후의 학생들은:
1-1) 1번 조건에 해당하는 자리가 한개라면: 바로 할당
1-2) 1번 조건에 해당하는 자리가 여러개라면: 2번 조건으로
2-1) 2번 조건에 해당하는 자리가 한개라면: 바로 할당
2-2) 2번 조건에 해당하는 자리가 여러개라면: 3번 조건으로
3-1) 3번 조건에 해당하는 자리가 한개라면: 바로 할당
3-2) 3번 조건에 해당하는 자리가 여러개라면: 4번 조건으로
4) 4번 조건에 해당하는 자리로 바로 할당
각각의 학생에 대해:
학생이 앉은 자리의 인덱스를 찾은 후 인접한 자리에 몇명 앉았는지 확인
점수 확인 후 더함
반복
=> [BOJ] 21608_상어 초등학교 / 골드5 / 80분 / O

week4/BOJ_20436/ZOAC 3_이동혁.py
- 백준 20436-ZOAC 3
구현, 시뮬레이션
왼손이 눌러야 될 키를 변수 'left'에 리스트로 선언
키보드 위치를 2차원 배열로 선언
마찬가지로 2차원 배열에서 인덱스를 찾아주는 함수(fin_index())를 선언
left_loc에 왼손의 위치를, right_loc에 오른손의 위치를 저장
입력받은 문자마다 왼손이 눌러야 되는지를 검사한 후, 눌러야 될 키의 위치를 반환 받아 거리를 더하고, 위치를 초기화
입력이 끝나면 total_distance를 반환
=> [BOJ] 20436_ZOAC3 / 실버4 / 20분 / O

week4/BOJ_2578/빙고_권은홍.java
=> [BOJ] 2578 빙고 / 실버4 / 90분 / X

week4/BOJ_20436/ZOAC3_권은홍.java
=> [BOJ] 20436 ZOAC3 / 실버4 / 100분 / O

week5/BOJ_2606/바이러스_홍지훈.py
- 백준 2606-바이러스
`dfs`
- edge 에 대한 정보만 주어졌으니 전체적으로 인접 리스트에 대한 정보를 갖는 graph 를 먼저 구해준다.
- dfs  는 방문 노드에 대한 정보를 갖고 있어 인접 리스트의 노드중 방문하지 않은 인접 노드가 있다면 해당 노드에서 dfs 를 재귀하는 방식으로 시작 노드를 기준으로 방문할 수 있는 모든 노드를 조회한다.
- 결과적으로 방문한 리스트중 1을 제외하여 바이러스가 퍼진 노드의 총 수를 구한다.
=> [BOJ] 2606_바이러스 / 실버3 / 50분 / O

week5/BOJ_11725/트리의 부모 찾기_홍지훈.py
- 백준 11725-트리의 부모 찾기
`그래프 이론`, `그래프 탐색`
> `bfs`, `dfs` 는 어떻게 적용이 가능한지 잘 모르겠어서 방문한 노드만 기록하며 부모 노드를 찾아봤습니다. 다른 분들 풀이가 궁금하네요
1. edge 정보가 주어져서 이를 토대로 인접 리스트 생성 - create_adjacency_list()
2. 인접 리스트에서 1번 루트 노드를 기준으로 순회하며 각 노드의 부모 노드가 무엇인지 찾는 메서드 생성 find_parent()
=> [BOJ] 11725_트리의 부모 찾기 / 실버2 / 50분 / O

week5/BOJ_1325/효율적인 해킹_홍지훈.py
- 백준1325-효율적인 해킹
`bfs`
> 접근은 처음에 코드를 짤 때부터 비슷했는데 걸리는 시간에 큰 차이가 있는 것 같습니다...
- bfs 를 사용하고자 해서 deque 을 통해 큐를 사용하고자 했습니다.
- 방문한 노드 처리를 해주고 큐에서 bfs 를 통해 방문하지 않은 노드를 방문할 때 count 를 1 증가시킵니다. 
- 이때 그래프는 A 가 B 를 신뢰하는 경우 B 로부터 이어진 노드들만 보면 되니 B 에서부터 A 로 가는 edge 들만 포함하는 그래프를 만들어 사용했습니다.
`통과하는 bfs`
```py
def bfs(start_v):
count = 1
visited = [False for _ in range(N + 1)]
visited[start_v] = True
queue = deque([start_v])
while queue:
cur_v = queue.popleft()  
for v in pairs[cur_v]:
if not visited[v]:
visited[v] = True
count += 1
queue.append(v)
return count
```
`시간초과한 bfs`
```py
def bfs(start_v):
visited = set([start_v])
queue = [start_v]
while queue:
cur_v = queue.pop(0)  
for v in pairs[cur_v]:
if v not in visited:
queue.append(v)
visited.add(v)
return len(visited)
```
=> 위의 코드처럼 set 을 사용해 값을 add 하는 …
=> [BOJ] 1325_효율적인 해킹 / 실버1 / 120분 / X

week5/PSG/택배 배달과 수거하기_홍지훈.py
- 프로그래머스 택배 배달과 수거하기
`그리디 알고리즘`
> 아직 이런 문제가 그리디 알고리즘을 사용해서 푼다고 바로 와닿지는 않네요..
- 배달을 갈때는 가장 먼 곳에서부터 배달을 전달하고 수거할때 역시 가장 먼 곳에서부터 빈 박스를 수거한다.
- 배달할 집이든 수거할 집이든 어느쪽이든 가야 하는 집이 가장 먼 곳까지는 가야한다. 그래서 둘중 가장 먼 곳에 있는 집까지의 거리 * 2 가 한번 배달을 나갈때 이동해야 하는 거리다.
- 한번 나갈때 cap 만큼 배달을 소모한다. 그때마다 각각의 큐에 배달 및 수거의 일을 처리한 내용을 업데이트한다.
- `last_valid_idx()` :  뒤에서부터 0이 아닌 값이 있는 마지막 집까지의 거리를 구한다.
- `get_distance()` : 배달 혹은 수거할 집중 가장 멀리 있는 집까지의 거리 * 2를 통해 한번 나갈때 이동해야 하는 거리를 구한다.
- `consume_capacity()` : 한번 나갈때 각 큐에서 정해진 용량만큼 소비해서 큐를 업데이트한다.
- `range(i, j, k)` : 항상 `range(i, j)` 나 `range(n)` 처럼만 사용하다 파라미터를 3개 사용한다면 간격을 설정할 수 있으니 뒤에서부터 역순으로 순회할 수 있다는 것을 알게되었습니다.
```py
stack = [1, 2, 3, 4, 5]
for i in range(len(stack) - 1, -1, -1):
print(stack[i]) # 5, 4, 3, 2, 1
```
=> [PSG] 택배 배달과 수거하기 / Lv. 2 / 120분 / O

week4/BOJ_22858/원상복구(small)_권은홍.java
- 백준 22858-원상복구
구현
S, D, P의 각각 배열을 생성하고 셔플횟수만큼 반복문을 돌며 P[D[인덱스]] = S[인덱스]를 저장하고 S에 P배열을 저장하여 반복한다. P배열을 출력한다.
=> [BOJ] 22858_원상복구 / 실버3 / 60분 / O

week4/BOJ_21608/상어초등학교_권은홍.java
- 백준 21608-상어초등학교
구현
학생 정보를 받아 좋아하는 학생 번호를 저장하고, Map에 현재학생 : 좋아하는 학생번호리스트를 넣는다. 자리를 순회하며 인접한 자리에서 좋아하는 학생 수, 인접 빈칸 수를 계산하여 현재 학생이 앉을 후보자리를 정한다. 자리 세팅 완료 후 만족도를 구한다.
=> [BOJ] 21608_상어초등학교 / 골드5 / 200분 / O

week4/BOJ_12933/오리_권은홍.java
- 백준 12933-오리 
그리디 알고리즘
오리 ArrayList를 생성하여 소리에 따라 각 오리를 하나의 인덱스에 저장한다. 소리 문자열을 받아 quack 순서대로 변경되도록 각 인덱스를 갱신하고, 문자열을 다 받은 후 모든 값이 k이면 개수를 세서 리턴한다.
=> [BOJ] 12933_오리 / 실버3 / 60분 / O

week5/바이러스_권은홍.java
백준 2606-바이러스
그래프, BFS
각 컴퓨터와 컴퓨터의 연결에 대응하는 그래프 생성
BFS로 탐색하며 컴퓨터가 탐색될 때마다 감염된 컴퓨터 수++
=> [BOJ] 2606 바이러스 / 실버3 / 50분 / O

week5/DFS와_BFS_권은홍.java
백준 1260-DFS와 BFS
그래프, dfs, bfs
인접리스트맵으로 각 정점의 인접리스트 저장, 각 인접리스트는 오름차순으로 정렬
간선 생성 시 이미 해당 정점의 인접리스트에 있는 정점이면 추가하지 않도록 함
출력 형식을 맞추기 위해 출력 문자열 printStr생성
DFS와 BFS탐색 실행 후 printStr 출력
=> [BOJ] 1260 DFS와 BFS / 실버2 / 60분 / O

week5/트리의_부모_찾기_권은홍.java
백준11725-트리의 부모 찾기
그래프, BFS
그래프 생성 시 각 정점의 부모가 들어가는 부모 리스트 parents 생성
Queue를 이용해 BFS 구현, 방문노드 체크 시 인접노드의 parents에 부모노드 저장
main에서 그래프 생성, BFS 실행 후 parents를 2부터 끝까지 출력
=> [BOJ] 11725 트리의 부모 찾기 / 실버2 / 30분 / O

week5/BOJ_1325/효율적인 해킹_권은홍.java
백준 1325-효율적인 해킹
방향 그래프, BFS
방향 그래프 구현
BFS에서 해킹한 컴퓨터 수 hackCnt 생성하고 노드 방문시마다 ++, hackCnt 리턴
가장 많은 컴을 해킹할 수 있는 번호 ArrayList result생성
현재 해킹 가능 최대 컴 수 maxCnt생성
1부터 N까지 bfs의 시작노드로 넣어서 돌려보며 maxCnt와 result갱신
result를 오름차순 정렬하여 print
=> [BOJ] 1325 효율적인 해킹 / 실버1 / 35분 / O

week6/BOJ_10994/별 찍기 - 19_홍지훈.py
- 백준 10994-별 찍기 - 19
`구현`, `재귀`
- 매번 중심부는 이전에 출력한 행렬과 같은 형태를 띄고 있으니 숫자가 더해지면 가장 바깥쪽 껍질만 새로 출력하는 식으로 코드를 구성했습니다.
- 그래서 처음 1, 2 까지 입력할 경우 출력은 하드코딩으로 넣어두고 그 이후 3부터는 재귀를 적용할 수 있어 매번 빈 행렬을 생성하고 -> 중심부를 이전 행렬로 교체한 뒤 -> 가장 바깥 껍질을 이어서 별로 채워주는 식의 접근을 생각했습니다.
> 규칙을 유추하라 해서 출력이 각 행 사이에 빈칸으로 채워진 행을 출력해야 하는줄 알았더니 착각이었네요;; 예제 출력만 보고 잘못 이해해서 다시 풀었네요..
=> [BOJ] 10994_별 찍기 - 19 / 실버4 / 40분 / O

week6/BOJ_1244/스위치 켜고 끄기_홍지훈.py
- 백준 1244-스위치 켜고 끄기
`구현`
- 각 상태의 스위치를 반전시키는 convert 메서드를 만들었습니다.
- 남학생의 경우 해당 인덱스의 스위치만 convert
- 여학생의 경우 해당 인덱스의 스위치를 convert 한 뒤, 양 옆 투 포인터를 만들어 0 ~ N - 1 범위 내에서 두 값이 일치하는한 계속 각각의 위치를 convert
- 20개씩 출력후 줄바꿈
=> [BOJ] 1244_스위치 켜고 끄기 / 실버 4 / 40분 / O

week6/BOJ_20164/홀수 홀릭 호석_홍지훈.py
- 백준 20164-홀수 홀릭 호석
- `재귀`, `구현`
- 숫자의 각 자리에 홀수가 몇개 존재하는지 구하는 함수 count_odd
- 두자리 수에서 각 자리의 수를 더한 값을 반환하는 함수 add_each_num
- 최소와 최대값을 찾는 함수 find_min_and_max
- 이 함수는 2개의 인자를 갖고 첫번째 인자는 현재 탐색하고자 하는 target, 두번째 인자는 현재 target의 각 자리에 존재하는 홀수의 수 
- 현재 숫자가 한자리 수일때 현재까지 카운트한 홀수의 수와 출력하고자 하는 최소, 최대치를 비교하여 갱신한다.
- 현재 숫자가 두자리 수일때 target 을 다음 재귀에 돌릴 next 값으로 갱신후 재귀
- 현재 숫자가 세자리 수일때 target 을 세가지 segment 로 분할후 next 값을 구하여 재귀
> 원래 모든 경우에서 카운트한 홀수의 수를 배열에 append 해두고 그중 min, max 값을 구했는데 처음부터 최소값, 최대값을 만들어두고 비교하면서 그 값만 갱신해주도록 수정했습니다. 
sys 에 maxsize 라는게 있었네요 지금까지 최대값 설정하려면 제약조건 보고 대략적인 값을 넣어줬는데 제공되는 최대값이 있었네요
```py
from sys import maxsize
```
참고로 maxsize 출력해보면 9223372036854775807 라는 수가 나옵니다.
=> [BOJ] 20164_홀수 홀릭 호석 / 골드5 / 120분 / X

week6/BOJ_3085/사탕 게임_홍지훈.py
- 백준 3085-사탕게임
`구현`, `브루트 포스`
- 현재 행에서 연속으로 존재하는 가장 긴 값을 구하는 함수 find_longest_length
- 길이를 초기화하는 함수 initiate
- 행렬을 transpose 하는 함수 transpose
- 현재 행렬에서 먹을 수 있는 사탕의 최대 개수를 구하는 함수 find_longest_in_matrix
- 가로로 인접한 사탕간에 교환하는 함수 exchange ( 단, 서로 다른 사탕간에 교환해야 하는 조건은 find_max_val 에서 처리
- 결과적으로 상근이가 먹을 수 있는 사탕의 최대 개수를 구하는 함수 solve
> 저는 다음 함수처럼 인자로 전달한 행렬의 내용을 바꾸고 그 결과를 반환하면 원본에는 영향이 없을 것이라 생각했는데 그렇지 않아서 deepcopy 를 사용했는데 좀 비효율적으로 느껴졌습니다. (공간) 
```py
def exchange(matrix, row, col):
matrix[row][col], matrix[row][col + 1] = matrix[row][col + 1], matrix[row][col]
return matrix
def find_max_val(matrix, max_value):
for row in range(len(matrix)):
for col in range(len(matrix[0]) - 1):
if matrix[row][col] == matrix[row][col + 1]:
continue
changed_matrix = exchange(copy.deepcopy(matrix), row, col)
max_value = …
```
=> [BOJ] 3085_사탕게임 / 실버2 / 60분 / O

week6/PSG/이모티콘 할인행사_홍지훈.py
- 프로그래머스 이모티콘 할인행사
`완전 탐색`
- 할인 쌍을 카티시안 곱 (itertools 의 product) 를 사용해서 구합니다.
- 각각의 할인 조합에서 각 유저가 이모티콘을 구입하게 되는 총 금액을 구하고 그 금액이 최대 금액보다 크거나 같다면 신규 서비스 등록자를 추가
- 그렇지 않다면 전체 판매액에 총 금액을 더한다.
- 리턴할 answer 와 지금 구한 신규 유저 및 총 판매액 리스트를 비교하여 큰 것을 반환한다.
- `itertools 의 product` : 카티시안 곱, repeat 에 주어진 숫자가 릴레이션 수로 보면 된다. 
```py
from itertools import product
for case in product([10,20,30,40], repeat=2):
print('case : ', case) # (10, 10) \n (10, 20) \n (10, 30) \n (10, 40) \n (20, 10) ...
```
> Lv. 2 도 어렵네요 ㅠㅠ 솔직히 시간내에 못풀어서 풀이를 참고했습니다...
=> [PSG] 이모티콘 할인행사 / Lv. 2 / 120분 / X

week6/BOJ_17413/단어 뒤집기 2_홍지훈.py
- 백준 17413-단어 뒤집기 2
`구현`
- 전체 문자열을 <> 태그가 있을 때와 없을때로 구분하여 출력한다.
- 태그가 없을때 빈 문자열이 나올 때까지 스택에 append 후 빈 문자열이 나오면 스택을 역순으로 바꾸고 마지막에 빈 문자열을 포함하여 출력한다.
- 태그가 있을 경우 태그가 열려있는 동안 스택에 쌓인 문자는 태그가 닫힐때 먼저 쌓인 순서대로 출력하고
- 태그가 닫혀있는 동안의 문자는 스택에 쌓아두었다가 태그가 다시 열리거나 끝날때 역순으로 출력한다.
=> [BOJ] 17413_단어 뒤집기 2 / 실버3 / 30분 / O

week6/BOJ_10994/별찍기-19_권은홍.java
백준 10994-별 찍기-19
구현
총 줄 수 = 한 줄 당 문자 수 rowNum 과 각 줄의 문자열을 저장할 Map 생성 
(그냥 배열로 만들었어도 될 듯 합니다)
총 줄수의 반만큼 for문을 돌며 index가 짝수일때/홀수일 때 문자열 구현 후 map에 넣음
map을 순서대로 출력 후 반대순서대로 출력
=> [BOJ] 10994 별 찍기-19 / 실버4 / 50분 / O

week6/BOJ_1244/스위치 켜고 끄기_이동혁.py
- 백준 1244-스위치 켜고 끄기
구현
스위치의 개수와 상태, 학생 수를 입력으로 받는다.
이때, 스위치의 상태를 나타내는 리스트는 인덱스 0번에 None을 넣음으로써, 1번 스위치가 1번 인덱스를 가르키도록 한다.
각각의 학생 성별과 스위치 번호에 대하여:
남학생이라면:
입력으로 받은 스위치 번호와 그 배수에 대해서 상태를 바꿈
여학생이라면:
left, right 변수 선언을 통해 two pointer 사용
left, right가 인덱스를 벗어나면 while문을 break하고, 아니라면 조건에 나와있는대로 수행
스위치의 상태를 20개 단위로 출력
=> [BOJ] 1244_스위치 켜고 끄기 / 실버4 / 40분 / O

week6/BOJ_10994/별 찍기 - 19_이동혁.py
- 백준 10994-별 찍기 - 19
구현
한 줄에 출력되는 최대 별 개수와 행의 개수는 항상 같고, 그 규칙은 1 + 4 * (n - 1)이라는 것을 이용.
입력이 1이면 별을 딱 한 개만 찍음.
첫째 줄에는 공백 없이 별을 찍고,
둘째 줄부터 중간 줄 전까지 나누어서 구현:
행이 짝수행인지, 홀수행인지 분기를 나누어 구현
중간 줄은 별 사이 공백 하나씩 출력
중간 줄 이후부터 마지막 줄 전까지 다시 나누어서 구현:
이전과 비슷한 코드인데, 하드코딩해서 설명하기는 조금 그러네요..ㅎㅎ
마지막 줄도 첫째 줄과 동일하게 공백 없이 별 출력
=> [BOJ] 10994_별 찍기 - 19 / 실버4 / 50분 / O

week6/BOJ_17276/배열 돌리기_홍지훈.py
- 백준 17276-배열돌리기
`구현`
- 회전하는 그룹을 8개로 분할하여 회전시 방향과 각 그룹 사이 얼만큼 간격의 그룹으로 이동해야 하는지를 확인한다
- 4개 방향 (주대각선, 부대각선, 가운데 열 그룹, 가운데 행 그룹 ) 외엔 그대로 유지하니 원본을 deepcopy 로 복사하고 움직이는 방향에 존재하는 셀만 복사본에 업데이트한다.
=> [BOJ] 17276_배열돌리기 / 실버2 / 120분 / O

week6/BOJ_17413/ 단어 뒤집기2_권은홍.java
- 백준 17413-단어 뒤집기2
구현
문자열을 받아서 뒤집은 결과를 출력하는 reverse() 함수 생성
태그 안에 있는지 여부 플래그 inTag, 단어를 임시적으로 담는 Stringbuilder word 생성
문자열을 받아 한 문자씩 확인하고 결과 문자열을 만든다.
- "<"인 경우 inTag =true
- ">"인 경우, inTag = false, word에 값이 있으면 reverse적용 후 추가
- 태그 안에 있는 경우 문자만 추가
- " "인 경우 word에 값이 있으면 reverse 후 추가
- 태그에 있지도 않고, 공백도 아닌 일반 문자열은 word에 추가
=> [BOJ] 17413 단어 뒤집기2 / 실버3 / 45분 / O

week6/배열돌리기_양승혜.py
백준 17276-배열돌리기
구현
1. 45도를 돌렸을 때의 함수를 설정했습니다.
- 빈 배열을 만들고
- 빈 배열에 입력받은 원본 배열을 deep copy합니다.
- 45도씩 몇 번씩 돌려야하는지 값을 구하여 (2번에서 설명) 그 값 만큼 for loop를 실행
- 문제 그대로 각 바꾸어야 하는 열, 행, 대각선을 새로운 맵에 새로이 값을 수정합니다.
2. 처음엔 각도가 양수일 때, 음수일 때로 나누어 함수를 작성하려고하였으나, 코드의 크기가 커지는 것 같아 다른 방법을 모색해보았습니다.
- 각도가 양수일 때 : (각도 // 45) 한 값만큼 rotate를 한다.
- 각도가 음수일 때 : (각도 // 45 + 8) % 8 한 값만큼 rotate를 한다.
- 예 : -45도일 때, (-45 // 45 + 8) % 8 = 7. 45도 회전을 7번하면 된다.
3. 입력값들을 받고, 답에 해당하는 맵을 추출, join을 이용하여 출력
=> [BOJ]17276_배열돌리기/실버2/180분/O

week6/PSG_이모티콘할인행사/이모티콘할인행사_조재은.py
- 프로그래머스 {문제번호}-{문제이름}
이모티콘 할인행사
DFS(재귀)
1. 모든 경우의 할인율 조합은 2차원이기 때문에 combination이나 permutations로 구하기가 어렵다. 그래서 dfs(재귀)를 활용하여 모든 경우에 대해 배열을 구성해주어야 한다.
2. 그렇게 모든 할인율의 경우의 수가 생겼다면, 문제 조건에 맞게 플러스 가입할지, 이모티콘만 구매할지 결정하고 그 중 가장 많이 가입하고 가장 많이 파는 경우의 수를 갱신해가다가 return해주면 된다.
- 모든 경우의 할인율 조합을 구함
- 만들어진 모든 조합을 하나씩 살펴봄
- 만약 유저의 제한금액 초과시 플러스 구매
- 현재 최대값을 넘어가면 갱신
=> [PSG] 이모티콘 할인행사 / 레벨2 / 120 / X

week6/BOJ_1244/스위치 켜고 끄기_조재은.py, week7/BOJ_1244/스위치 켜고 끄기_조재은.py
1244 스위치 켜고 끄기
구현,시뮬레이션
1. 스위치 상태, 켜저 있으면 1, 꺼져 있으면 0, 사이에는 빈칸
2. 남학생 : 받은 수의 배수에 해당하는 모든 스위치를 현재 상태의 반대로 만든다. (꺼져있으면 키고, 켜저있으면 끈다)
3. 여학생 : 받은 수를 중심으로 좌우가 서로 다은 상태일때까지 모든 스위치를 반대로 만든다.
4. 스위치의 상태: [1 1 1 1 0] 이고 주어진 수는 3이면 2,4 번째가 같은 상태미으로 반대로 만들고, 그 이후에 1, 5번째가 다른 상태이므로 여기서 끝낸다.
5. 받은 스위치의 번호를 기준으로 -i와 +i를 비교하여 같으면 스위치의 상태를 반대로 만들어주면 된다.
=> [BOJ] 1244_스위치 켜고 끄기 / 실버 4 / 60분 / X 

week7/다리 놓기_양승혜.py
- 백준 1010 - 다리 놓기
- combination, dp
<1번 풀이>
- 다리끼리 서로 겹쳐질 수 없다고 해서 nCr(조합, combination)로 풀어야겠다고 생각했습니다. 
- nCr = n! / (n - r)! * r!
- factorial(n) 함수를 만들고
- 위의 공식에 따라 값을 도출했습니다.
<2번 풀이>
- 1번 풀이에 따라 표를 그려보았더니
서(n)/ 동(m) | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | --
1 | 1 | 2 | 3 | 4 | 5 | 6
2 | x(m은 n보다 같거나 커야함) | 1 | 3 | 6 | 10 | 15
3 | x | x | 1 | 4 | 10 | 20
4 | x | x | x | 1 | 5 | 15
5 | x | x | x | x | 1 | 6
- 위와 같았는데,
- d[n][m] = d[n][m - 1] + d[n - 1][m - 1]이라는 공식이 나왔습니다.
- 이를 바탕으로 dp로 풀었습니다.
=> [BOJ] 1010_다리 놓기 / 실버5 / 80분 / O

week7/BOJ_2839/설탕배달_조재은.py
2839_설탕배달
그리디 알고리즘,다이나믹 프로그래밍,수학
5의 배수이면 조건문
5로 나눈 몫을 구해야 정수가 됨
=> [BOJ] 2839_설탕배달 / 실버4 / 60분 / O

week7/BOJ_1010/다리놓기_조재은.py
1010 다리놓기
다이나믹 프로그래밍,수학,조합론
조합을 이용해서 해결할 수 있다. 서로 다른 m개에서 n개를 고르는 경우의 수를 구해준다.
- factorial을 정의하고 조합을 이용하여 다리의 개수를 구한다.
- m C n = m!/n!*(m-n)!
=> [BOJ] 1010_다리놓기 / 실버5 / 60분 / O

week6/BOJ_17413/단어뒤집기2_조재은.py
17413 단어 뒤집기 2
구현,문자열,스택,자료 구조
1. 열린 괄호를 만나면, 닫힌 괄호를 만날 때 까지 검사
2. 닫힌 괄호를 만난 후 인덱스를 하나 증가시킨다.
3. elif word[i].isalnum(): 숫자나 알파벳을 만나면 true, 아니면 false
4. 숫자, 알파벳 범위에 있는 것들을 뒤집는다
5. 괄호도 아니고 알파, 숫자도 아닌 것 즉, 공백이면 그냥 i 증가
6. reverse, isalnum 함수 사용
7. isalnum : 문자열이 영어, 한글 혹은 숫자로 되어있으면 참 리턴, 아니면 거짓 리턴.
출처: https://it-neicebee.tistory.com/43 [IT’s Portfolio:티스토리]
=> [BOJ] 17413_단어 뒤집기 2 / 실버3 / 60분 / O

week5/BOJ_1260/DFS와 BFS_이동혁.py
- 백준 1260-DFS와 BFS
인접리스트, 그래프, DFS, BFS
각각의 노드에 대한 인접리스트를 생성
노드의 숫자가 가장 작은 것부터 순회할 수 있도록 인접리스트의 요소를 오름차순 정렬
DFS: 시작 노드부터 순회해서, 재귀로 구현
BFS: 큐를 사용해 구현
=> [BOJ] 1260_DFS와 BFS / 실버2 / 50분 / O

week5/BOJ_2606/바이러스_이동혁.py
- 백준 2606-바이러스
그래프, DFS
연결된 노드 쌍을 입력으로 받아 인접 행렬을 만듦
dfs 알고리즘을 함수로 구현해 1번 컴퓨터에서 시작하는 dfs를 수행
방문한 모든 노드 중 1번 컴퓨터 자신을 제외한 개수를 리턴
=> [BOJ] 2606_바이러스 / 실버3 / 60분 / O

week6/스위치 켜고끄기_양승혜.py
- 백준 1244-스위치 켜고 끄기
구현, 투포인터
1. 스위치가 0 -> 1, 1 -> 0 으로 바뀌는 코드가 반복되어서 change라는 함수로 만들었습니다.
2. 스위치를 인덱스로 접근할 때 헷갈려서 맨 앞에 '-1'값을 붙였습니다. (-1은 아무 의미도 없습니다)
3. 남자면(1이면) for문을 이용해서 뽑은 숫자부터 뽑은 숫자만큼의 간격만 change되도록 하였습니다.
4. 여자면(2이면) left, right로 포인터를 두 개를 설정하여 값이 같은지, 인덱스가 알맞은지 비교하며 코드를 작성하였습니다.
5. 20개씩 나누어 출력하는 게 어려워서 이 부분은 사실 참고를 해서 풀었습니다 ㅎㅎ....
=> [BOJ] 1244_스위치 켜고 끄기 / 실버 4 / 100분 / O

week6/단어 뒤집기2_양승혜.py
- 백준 17413-단어 뒤집기 2
스택
1. 빈 스택과 정답을 담을 빈 문자열을 생성합니다. 그리고 주어지는 값이 `<>`안에 있는지 없는지 확인할 수 있는 'flag'라는 변수를 설정합니다.
2. 주어진 문자열을 한 개씩 돌며 만약 '<'라면, 괄호가 시작되므로 flag의 값을 True로 변환하고, 스택 안에 값이 존재한다면 pop()을 통해 answer에 '거꾸로' 더해줍니다.
3. '>'을 만나면 괄호가 끝나므로 flag를 false로 바꾸고, '>'는 그대로 answer 문자열에 넣습니다.
4. 만약 " "(빈칸)을 마주치고, '<>'밖에 존재한다면(flag가 false라면) stack에 쌓여있는 문자들을 pop()을 통해 answer문자열에 거꾸로 저장해줍니다.
5. 이 모든 조건을 만족하지 않고, flag라면, 즉, 괄호 안에 있는 값이라면 string을 그대로 answer에 순서대로 더해주고,
6. 만약 괄호 밖에 있는 값이라면 string을 stack안에 집어 넣습니다.
7. string을 다 돌고나서도 stack에 값이 남아 있다면, `stack.pop()`을 통해 answer에 거꾸로 값을 저장합니다.
=> [BOJ] 17413_단어 뒤집기 2 / 실버3 / 65분 / O 

week6/사탕게임_양승혜.py
- 백준 {3085}-{사탕게임}
- 구현, 브루트포스
- 정말 한 땀 한 땀 브루트포스로 푼 풀이입니다...😂
1. 처음엔 2중 for문을 사용하여 바로 옆, 바로 아래의 값들을 하나씩 다 바꾸었습니다. 그랬더니 시간초과가 났습니다.
2. 그래서 만약 바로 옆 또는 바로 아래의 값이 같다면 for문을 수행하지 않도록 조건을 추가하였더니 통과가 되었습니다.
3. 최대로 먹을 수 있는 사탕의 개수를 산출하는 함수를 따로 만들었습니다. -> `check()`
=> [BOJ] 3085_사탕게임 / 실버2 / 135분 / O

week7/설탕 배달_양승혜.py
- 백준 2839-설탕 배달
- greedy, dp
- greedy
1. total이 0보다 클 때까지만 while문 작동
2. 5로 나눈 나머지가 0이라면 bag에 5로 나눈 몫을 더하고, bag를 print하고, break를 통해 while문을 빠져나온다.
3. while문을 빠져나오지 못했다면 total에서 3을 빼고, bag에 1을 더한다
4. 만약 whlie문에서 break가 실행되지 않으면 -1을 print 한다.
- dp
1. 입력된 수 + 1 한 값 만큼 -1을 채운 리스트를 만든다.
2. 3이상인 수만 입력값으로 주어지므로, 3부터 위에서 만든 리스트의 길이만큼 인덱스를 순회한다.
3. 이 문제의 규칙은 `dp[i] = 1 + min(dp[i - 3] + dp[i - 5])` 이다.
4. 위의 규칙에 따라 if문을 조건을 설정한다.
5. 입력된 수에 해당하는 리스트의 인덱스 값을 출력한다.
=> [BOJ] 2839_설탕 배달 / 실버4 / 75분 / O

week7/BOJ_17626/Four Squares_조재은.py
17626_Four squares 
다이나믹 프로그래밍,브루트포스 알고리즘
combinations_with_replacement : 입력된 반복 가능한 객체에서 중복을 허용하여 지정된 길이의 모든 조합을 생성합니다.
이 함수는 주어진 반복 가능한 객체에서 원소를 선택하여 지정된 횟수만큼 반복하여 조합을 만들 수 있도록합니다.
- 제곱수면 1
- 제곱수 두개를 더해서 만들 수 있는 수면 2
- 제곱 수 중, n에서 제곱수를 뺀 수가 제곱수 두개를 더해서 만들 수 있는 수면
=> [BOJ] 17626_Four squares / 실버3 / 100분 / O

week6/홀수 홀릭 호석_양승혜.py
- 백준 20164-홀수 홀릭 호석
- 재귀, 구현
1. 입력을 string 형식으로 받는다.
2. 홀수의 개수를 저장할 'count' 빈 배열을 초기화한다.
3. 해당 숫자가 홀수인지 확인하기위한 함수 -> isodd()를 만든다.
4. 입력 받은 숫자의 길이가 1일때, 2일때, 3이상일 때로 나누어 숫자를 쪼개고, 홀수의 총 개수를 구할 수 있는 함수를 만든다. -> 재귀 이용
5. 홀수의 총 개수를 담은 count 배열의 min 값과 max 값을 출력한다.
=> [BOJ] 20164_홀수 홀릭 호석 / 골드5 / 50분 / O

week6/BOJ_20164/홀수 홀릭 호석_권은홍.java
=> [BOJ] 20164 홀수 홀릭 호석 / 골드5 / 200분 / O

week7/스티커_양승혜.py
- 백준 9465-스티커
- dp
1. 지그재그로 값을 더하여 제일 큰 값을 도출해내는 문제였다.
2. dp를 사용하여 전의 값들을 후의 값에 더해나가는 풀이다.
3. 따라서 0열과 1열의 마지막 값 중 큰 값을 산출하면 되는 문제였다.
4. 하지만 문제의 예시처럼 중간에 스티커를 뛰어넘을 수도 있었다.
5. 두 개~ 세 개를 뛰어 넘을 수 있나 실험을 해보았더니 무조건 한 칸만 뛰어 넘는 것이 가장 큰 값을 도출할 수 있었다.
6. 따라서 **아랫 줄**의 합을 구하기 위해서는 **윗 줄의 전 값**과 그 **전전 값**을 비교, **윗 줄**의 합을 귀하기 위해서는 **아랫 줄의 전 값**과 **전전 값**을 비교하여 더 큰 값을 더하면 되었다.
=> [BOJ] 9465_스티커 / 실버1 / 60분 / O

week7/BOJ_1010/다리 놓기_이동혁.py
- 백준 1010-다리놓기
수학, 다이나믹 프로그래밍, 조합
combintaions_count() 함수 정의: nCr의 조합의 개수를 구하는 함수
동쪽에 있는 m개의 사이트에서, n개의 사이트를 구하는 조합만 구하면 각각의 다리가 어떤 사이트에서 어떤 사이트로 이어져야 하는 지는 알아서 지정됨
따라서 mCn의 조합의 개수만 구한다.
=> [BOJ] 1010_다리 놓기 / 실버5 / 50분 / O

week7/BOJ_2839/설탕 배달_이동혁.py
- 백준 2836-설탕 배달
수학, 다이나믹 프로그래밍, 그리디 알고리즘
5킬로 설탕의 개수를 big, 3킬로 설탕의 개수를 small로 정의
5킬로 설탕의 개수를 최대로 하는 것이 목적이므로, big에 n을 5로 나눈 몫을, small은 0 으로 초기화한다.
while 문을 돌면서 n에서 5키로 설탕양을 뺀 키로 수가 3으로 나누어진다면 break
아니면 5키로 설탕을 하나씩 줄이면서 같은 if 문을 순회
5키로 설탕의 개수가 0보다 작아진다면 만들 수 있는 조합이 없는 것이므로 -1 프린트
=> [BOJ] 2839_설탕 배달 / 실버4 / 60분 O

week7/BOJ_17626/Four Squares_이동혁.py
- 백준 17626-Four Squares
다이내믹 프로그래밍, 브루트포스 알고리즘
n은 어떤 자연수의 제곱근보다 더 작은 수의 조합으로 이루어지므로 1부터 n의 제곱근을 소수점 첫째자리에서 버림한 자연수까지 리스트로 만듦
이후 제곱수의 조합을 1개부터 4개까지 차례로 for문을 수행하고, 이미 값을 찾았으면 break
for문:
조합되는 제곱수의 개수에 따라, 모든 조합을 생성.
조합의 요소를 더한 값이 n과 같으면 출력, break
브루트포스와 가까운 방법인 것 같은데 시간 초과로 풀리지 않았슴.
어떤 자연수든 제곱수의 조합으로 표현된다는 점에서 큰 수를 작은 수의 제곱수들의 합으로 표현하고, 병합하는 과정을 거치는 DP문제로 풀수 있을 것 같은데 생각해봐도 코드로 구현은 못 해서 포기
=> [BOJ] 17626_Four Squares / 실버3 / 90분 / X

week8/격자상의 경로_양승혜.py
- 백준 10164-격자상의 경로
- dp
- 하하.. 점화식 세우는 건 그렇게 오래걸리지 않았는데 'O'가 존재할 때 새로이 좌표를 할당하는 부분이 너무 오래걸렸습니다...😇
(for문 여러번 안 만들고 함수 한 개로 다 구현하려다가..)
- 점화식
- 예전에 확률과 통계 수업에서 최단거리 경우의 수 구하는 방법이 떠오르는 문제였습니다.
- 그래서 이번기회에 찾아보았습니다!
- 참고 블로그 : https://m.blog.naver.com/parkhc1992/220669287080
- 표로 그려보자면 아래와 같습니다.
- 행이나 열의 인덱스가 0이면 칸에 다 1을 넣고, 칸을 내려가며 위, 왼쪽 칸의 숫자를 더한 값을 넣습니다.
- 만약 'O'가 존재하면, 즉, k에 값이 할당되어있으면, k에 해당하는 (행, 열) 인덱스를 구하고
- (k의 행, 열 인덱스의 값 * k의 행, 열부터 m, n까지의 경로) 를 하면 값이 나옵니다.
=> [BOJ] 10164_격자상의 경로 / 실버1 / 135분 / O

week8/과일서리_양승혜.py
- 백준 17213-과일서리
- 중복 조합
- 중복해서 여러 과일을 훔쳐도되고, 순서는 상관 없는 점을 활용하여 중복 조합으로 문제를 풀어야겠다고 생각했습니다.
- n가지의 과일이 있을 때, m개의 과일을 훔칠 수 있지만, n가지의 과일 중에서 꼭 한 개의 과일은 훔쳐야하므로 훔쳐야하는 전체 과일의 수는 m-n으로 잡았습니다.
- 중복 조합 공식에 따르면 n H m - n 이 되는데, 이를 combination공식으로 바꾸면 n + (m - n) - 1 C m - n이 됩니다. 
- 위의 공식에 따라 itertools안에 있는 combination을 사용해서 문제를 풀었습니다.
- 중복 조합을 참고한 블로그 : https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=freewheel3&logNo=220785417706
=> [BOJ] 17213_과일서리 / 실버2 / 45분 / O

week9/BOJ_11403/경로 찾기_홍지훈.py
- 백준 11403-경로 찾기
`다익스트라 최단 경로`, `우선 순위 큐`, `플로이드 - 워셜`
앞의 특정 거리의 도시 찾기 문제와 거의 유사해보여서 풀이 방식이 그렇게 많이 바뀌지 않았습니다.
다익스트라가 특정 노드에서 특정 거리의 노드를 찾을 수 있도록 해주니 모든 노드에서 각 노드까지의 최단경로를 구하는 식으로 접근했습니다.
제출후 `플로이드 워셜 최단경로 알고리즘` 에 대해 알게되었습니다.
`다익스트라 알고리즘`이 `한 지점에서 다른 특정 지점까지의 최단 경로`를 구할때 사용한다면 
`플로이드 워셜 최단경로 알고리즘`은 `모든 지점에서 다른 모든 지점까지의 최단 경로를 모두 구해야 하는 경우`에 사용할 수 있는 알고리즘이라고 합니다.
단, 성능이 그리 좋은 알고리즘은 아닌 것 같습니다. 최단경로를 갱신하려면 O(N^3) 의 시간복잡도가 필요합니다.
=> [BOJ] 11403_경로 찾기 / 실버1 / 30분 / O

week9/BOJ_1058/친구.py
- 백준 1058-친구
`플로이드 - 워셜 최단경로`
`플로이드 - 워셜` 알고리즘은 모든 지점에서 다른 모든 지점까지의 최단 경로를 모두 구해야 하는 경우에 사용합니다.
1. 아직 친구관계가 몇 단계에 걸쳐 존재하는지 모르는 경우 완전히 단절된 경우 무한의 값을 할당합니다. 이겨서는 `int(1e9)` 의 값을 할당했습니다.
```py
INF = int(1e9)
N = int(input()) # N : 사람의 수
graph = [[INF] * (N + 1) for _ in range(N + 1)]
```
> 인덱스와 사람을 동일하게 보기 위해 앞에 1개의 의미없는 공간을 할당했습니다.
2. 친구관계를 확인하기 위해 직접적인 친구관계의 경우 graph 에서 값을 INF -> 1 로 값을 변경합니다.
```py
for i in range(1, N + 1):
info = list(input().rstrip())
for j, val in enumerate(info):
if val == 'Y':
graph[i][j + 1] = 1
```
3. 자기 자신과는 친구가 아닌 점을 반영합니다.
```py
for a in range(1, N + 1):
for b in range(1, N + 1):
if a == b:
graph[a][b] = 0
```
4. 플로이드 - 워셜 알고리즘은 직접적인 연결보다 한다리 걸쳐서 가는것의 거리 / 비용이 더 적을 경우 갱신하는 알고리즘이라 O(N^3) 의 시간복잡도로 탐색합니다.
```py
for k in range(1, N + 1):
for a in range(1, N + 1): …
```
=> [BOJ] 1058_친구 / 실버2 / 30분 / O

week9/BOJ_18243/Small World Network_홍지훈.py
- 백준 18243-Small World Network
`플로이드 - 워셜`
> 1058 친구 문제와 너무 비슷한 문제를 선정했었네요.. 죄송합니다.. 문제 풀이 방식이 동일하고 7보다 큰 관계가 존재하는지 유무만 판단해서 결과를 출력했습니다.
=> [BOJ] 18243_Small World Network / 실버1 / 10분 / O

week9/BOJ_13549/숨바꼭질 3_홍지훈.py
- 백준 13549-숨바꼭질 3
`다익스트라`
- 걷는 것과 순간이동을 하는 경우를 경로와 거리로 생각했습니다.
- 걷는 경우 X 에서 X + 1 혹은 X - 1 의 노드로 이동하되, 그때의 거리는 1
- 순간이동을 하는 경우 X 에서 X * 2 의 노드로 이동하되, 그때의 거리는 0
- answer 라는 딕셔너리에 최단거리를 기록합니다.
```py
MAX = 100000
answer = {node: INF for node in range(MAX + 1)}
```
이 문제는 수빈이의 지점에서 동생의 지점까지 가는 최단거리 (최단시간) 을 구하는 문제라서 answer 의 key 가 동생이 존재할 수 있는 위치를 의미합니다.
- 만약 동생이 최소, 최대 지점에 존재한다면 + 1, -1 로만 동생을 찾을 수 있습니다.
- 그 외의 경우에 + 1 혹은 - 1, 그리고 X * 2 가 MAX 보다 작거나 같다면 순간이동으로도 동생을 찾을 수 있습니다.
```py
graph = [[] for i in range(MAX + 1)]
for i in range(MAX + 1):
if i == 0:
graph[i].append((1, 1))
elif i == MAX:
graph[i].append((MAX - 1, 1))
else:
graph[i].append((i + 1, 1))
graph[i].append((i - 1, 1))
if i * 2 <= MAX:
graph[i].append((i * 2, 0))
```
- 이후엔 heap 자료구조를 이용해서 현재 노드를 거쳐 다른 노드로 이동하는 거리가 더 짧을 경우 최단거리 …
=> [BOJ] 13549_숨바꼭질 3 / 골드5 / 20분 / O

week9/BOJ_13549/숨바꼭질 3_최재선(2).js, week9/BOJ_13549/숨바꼭질 3_최재선.js
- 백준 13549-숨바꼭질 3
- bfs
- maxSize를 dest(도착지) 위치 * 2 + 1로 초기화
- maxSize 기반 visited 선언
- Queue에 현재 동생 위치로 초기화
- bfs에서 한칸씩 순차적으로 동생이 갈 수 있는 위치 순회
===========================================
- 백준 13549-숨바꼭질 3(2)
- bitwise
- 출발지를 2배씩 증가하여 도착지 바로 전 지점과 후 지점을 탐색
- 해당 위치에서 도착지를 뺀 차이를 저장
- getCount 함수 선언
- 2진수를 활용하여 가용 가능한 길이의 제일 처음과 가용 가능한 길이를 뺀 나머지를 10진수로 변환하여 저장
- 그 후에 맨 끝 1에 대해서, 다음자리 1이 있다면 무조건 1을 더하는 식으로 compress
=> [BOJ] 13549 숨바꼭질 3 / 골드5 / 50분 / O || [BOJ] 13549 숨바꼭질 3(2) / 골드5 / 150분 / O

week9/PGS_k진수에서 소수 개수 구하기/k진수에서 소수 개수 구하기.js
- 프로그래머스 k진수에서 소수 개수 구하기
- 주어진 숫자를 toString()을 사용하여 k진수로 변경
- 0을 기준으로 split후 Number 타입 변환
- prime(소수) 판별하는 isPrime 함수 선언
=> [PGS] k진수에서 소수 개수 구하기 / 10분 / O

week9/BOJ_18243/Small World Network_최재선.js
- 백준 18243-Small World Network
- bfs
- 사람마다 bfs로 순회하여 정해진 depth가 넘어갈 경우, break
=> [BOJ] 18243 Small World Network / 실버1 / 20분 / O

week9/BOJ_1446/지름길_최재선.js
- 백준 1446-지름길
- bfs
- dp
- 시작 위치(0) 에서 N위치로 가는 거리의 최솟값 저장 dp 선언
- graph에 정보 저장
- dp 순회하며, dp로 올 수 있는 경우들 중 최솟값 저장
=> [BOJ] 1446 지름길 / 실버1 / 30분 / O

week9/BOJ_1058/친구_최재선.js
- 백준 1058-친구
- bfs
- availableDepth에 문제 조건인 2선언
- 최초 탐색 위치에서 connection을 토대로, 갈 수 있는 위치 bfs로 depth 1씩 증가 순회
- depth가 availableDepth 넘는 순간 종료
=> [BOJ] 1058 친구 / 실버2 / 10분 / O

week9/BOJ_18352/특정 거리의 도시 찾기_최재선.js
- 백준 18352-특정 거리의 도시 찾기
- bfs
- graph에 갈 수 있는 경로 저장
- 있을 수 있는 위치들 (poses) 선언 및 X로 초기화
- 현재 간 거리(length) 0을 초기화
- 1칸씩 전진하며 length가 K가 되너가 poses의 길이가 0이면 종료
=> [BOJ] 18352_특정 거리의 도시 찾기 / 실버2 / 60분 / O

week9/BOJ_11403/경로 찾기_최재선.js
- 백준 11403-경로 찾기
- bfs
- graph에 갈 수 있는 경로 저장
- graph 순회하여 갈수 있는 경로 bfs로 탐색 후 저장
=> [BOJ] 11403_경로 찾기 / 실버1 / 15분 / O

week9/BOJ_18243/Small World Network_이은혁.py
- 백준 18243_Small World Network
bfs
bfs로 순회하며 depth가 6보다 커질 경우, flag 변수 False 처리
=> [BOJ] 18243_Small World Network / 실버1 / 60분 / O

week9/BOJ_13549/숨바꼭질 3_이은혁.py
- 백준 13549_숨바꼭질 3
bfs
1. 현재 위치와 시간을 큐에 넣고 bfs를 돌림
2. 반복문 내에서 현재 위치가 K인 경우, 즉 수빈이의 위치인 경우 break
3. 아닌 경우 for문 실행 => 움직이는 경우가 x-1, x+1, 순간이동로 나눠 3번 루프실행
4. 다음의 위치와 다음 시간을 next와 next_sec으로 받고,  조건에 부합하는 경우 q에 추가
=> [BOJ] 13549_숨바꼭질 3 / 골드5 / 180분 / O

week9/BOJ_18243/Small World Network_양승혜.py
- 백준 18243-Small World Network
- 플로이드-와샬
- 몇 번을 걸쳐 친구가 될지 저장할 그래프 만듦
`graph = [[1e9] * n for _ in range(n)]`
- 나 자신과는 친구가 될 수 없기에 행과 열 값이 같으면 0, 쌍방향 그래프이므로 input에서 주어진 정점끼리는 1로 값을 갱신한다.
- 플로이드-와샬 알고리즘을 사용하여 그래프의 현재 값과, 중간 값을 거쳤을 때의 비용을 비교해 최소값을 그래프의 값으로 갱신한다.
- 마지막으로 그래프를 돌며 6보다 큰 값이 있으면 "Big World!", 6보다 작으면 "Small World!"를 출력한다.
=> [BOJ] 18243_Small World Network / 실버1 / 25분 / O

week9/PSG_k진수에서 소수 개수 구하기/k진수에서 소수 개수 구하기_양승혜.py
- 프로그래머스 - k진수에서 소수 개수 구하기
- 에라토스테네스의 체
- n을 k진법으로 바꾸는 함수 change()
- '0'을 기준으로 split하여 새로운 숫자 리스트를 만들고, 그 리스트를 돌며 소수인지 판별한다.
- 소수인지 판별할 때 검색시간을 줄이기위해 해당 숫자의 제곱근까지의 숫자만 돌며 나누고, 만약 나머지가 0이 된다면 'error'에 1을 더한다. 
- 쓰면서 발견한건데, error += 1 코드 밑에 break를 써주었으면 더 좋았을 것 같다.
- 만약 error가 0이라면 answer에 1을 더하고, answer를 return 한다.
=> [PSG] k진수에서 소수 개수 구하기 / 20분 / O

week9/BOJ_1446/지름길_양승혜.py
- 백준 1446-지름길
- dp
- 다익스트라로 풀고싶었는데 뭔가.. 변수가 계속 꼬여서 그런지 결국엔 dp로 풀었습니다ㅠㅠ
- 고속도로의 길이만큼 숫자를 담은 graph를 만든다. -> cost를 담은 리스트
- 고속도로의 길이만큼 for - in loop를 돌면서 현재 위치로 가기까지의 cost 와 그 전 위치 + 1한 값 중 작은 값을 graph의 값을 갱신한다.
- input에서 주어진 시작 지점과 현재 검증 중인 거리와 같을 때 cost를 비교하여 그래프의 값을 갱신한다.
- 그래프의 가장 마지막 값을 print하여 값을 도출한다.
=> [BOJ] 1446_지름길 / 실버1 / 120분 / O

week9/BOJ_11403/경로 찾기_양승혜.py
- 백준 11403-경로찾기
- 플로이드-워셜
- graph에 input값들을 넣어 2차원 배열형식으로 만들고,
- 플로이드-워셜 알고리즘을 이용하여 '지나가는 정점'을 기준으로 출발하는 정점, 도착 정점을 for-in loop로 돌면서 간선이 존재하면 1로 값을 갱신한다.
=> [BOJ] 11403_경로 찾기 / 실버1 / 35분 / O

week9/BOJ_18352/특정 거리의 도시 찾기.py
- 백준 18352-특정 거리의 도시 찾기
- 다익스트라
- 그래프에 주어진 정보를 저장
- 다익스트라 알고리즘을 활용한 dijkstra(start) 함수
- 'flag'를 사용해서 만약 목표로 한 거리와 같은 도시를 찾으면 인덱스 출력, 아니면 -1 출력
=> [BOJ] 18352_특정 거리의 도시 찾기 / 실버2 / 85분 / O

week10/BOJ_1969/DNA_홍지훈.py
- 백준 1969-DNA
`그리디 알고리즘`, `브루트 포스`
```py
from itertools import product
import sys
input = sys.stdin.readline
N, M = map(int, input().rstrip().split()) # N : DNA 의 수, M : 문자열의 길이
min_hamming_sum = M * N
min_dna = ''
def calc_hamming_dist(dna1: str, dna2: str) -> int:
count = 0
for char1, char2 in zip(dna1, dna2):
if char1 != char2:
count += 1
return count
dna_info = ['A', 'C', 'G', 'T']
dna_list = [''.join(dna) for dna in list(product(dna_info, repeat=M))] # 가능한 dna 후보 리스트
dna_input = []
for _ in range(N):
dna_input.append(input().rstrip())
for dna in dna_list:
hd_sum = 0
for input in dna_input:
hd_sum += calc_hamming_dist(dna, input)
if hd_sum < min_hamming_sum:
min_dna = dna
min_hamming_sum = hd_sum
print(min_dna)
print(min_hamming_sum)
```
- M 의 길이를 갖는 DNA 중 모든 가능한 DNA 를 갖는 dna_list 를 …
=> [BOJ] 1969_DNA / 실버4 / 60분 / O

week10/BOJ_2961/도영이가 만든 맛있는 음식.py
- 백준 2961-도영이가 만든 맛있는 음식
- `조합`, `완전탐색`
- 조합을 통해 재료중 1개, 2개, N 개를 고르는 모든 경우를 완전탐색하여 차이가 최소가 될때의 값을 반환했습니다.
=> [BOJ] 2961_도영이가 만든 맛있는 음식 / 실버2 / 20분 / O

week10/BOJ_2503/숫자 야구_김선진.py
- 백준 2503-숫자 야구
- 구현
- 순열
- 1~9까지 서로 다른 숫자 세 개로 구성된 세 자리 수의 모든 경우의 수를 담는 numbers 리스트 생성
- 민혁이가 질문한 숫자와 비교해서 strike와 ball 개수 계산
- 영수가 답해준 strike와 ball의 개수와 동일하지 않으면 numbers 리스트에서 해당 수를 제거한다.
=> [BOJ] 2503_숫자 야구 / 실버3 / 120분 / O

week10/BOJ_2615/오목_홍지훈.py
- 백준 2615-오목
`구현`
- 가로, 세로, 대각선 방향으로 5개의 돌의 색이 일치하는지 확인합니다.
- 한 돌에서 동시에 6돌이상과 다른 방향으로 5목이 존재할 수 있어서 조건을 만족하면 오목, 그렇지 않으면 오목이 아닌 것으로 판단하도록 했습니다.
- 범위의 가장자리에선 오목 진행방향중 한쪽 방향으로만 6목이 존재할 가능성이 있고 범위 내부에선 양쪽 방향으로 6목이 존재할 가능성이 있어 각각 따로 조건을 걸어 5목 여부를 판단했습니다.
> 너무 비효율적인것 같다는 생각이 드는 풀이였네요..
=> [BOJ] 2615_오목 / 실버1 / 70분 / O

week10/BOJ_15661/링크와 스타트_홍지훈.py
- 백준 15661-링크와 스타트
`구현`
시간내에 풀지 못해서 다른 분의 풀이를 참고하였습니다.
이 풀이는 Sij + Sji 를 전체 total 에서 나머지를 빼는 식으로 접근합니다.
1. 각 행의 합을 담는 row 배열
2. 각 열의 합을 담는 col 배열
3. i 번째 행의 합 + i 번째 열의 합을 담는 arr 배열
4. 행렬 모든 수의 합 total
=> [BOJ] 15661_링크와 스타트 / 골드5 / 120분 / X

week10/BOJ_1969/DNA_양승혜.py
- 백준 1969-DNA
- 구현
- 주어진 input들을 보았을 때, 
0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | --
T | A | T | G | A | T | A | C
T | A | A | G | C | T | A | C
A | A | A | G | A | T | C | C
T | G | A | G | A | T | A | C
T | A | A | G | A | T | G | T
T : 4개<br>A : 1개 | A : 4개<br>G : 1개 | T : 1개<br>A : 4개 | G : 5개 | A : 4개<br>C : 1개 | T : 5개 | A : 3개<br>C : 1개<br>G : 1개 | C : 4개<br>T : 1개
가장 많이 등장하는 알파벳이 Hamming Distance의 합이 가장 작은 DNA가 된다는 것을 발견했습니다.
- 그래서 등장할 수 있는 알파벳들의 수를 세고, 가장 수가 많은 알파벳을 해당 인덱스의 알파벳으로 선정했습니다.
- 이때, 만약 max의 값이 같으면 사전순으로 가장 앞서는 것을 출력해야하기에 아예 if문 설계를 알파벳 사전순으로 했습니다.
- 사실... 이중 딕셔너리로 해보고싶어서 구현을 이리저리 하다가 결국엔 2중 리스트로 처리했습니다 ^_ㅠ... 생각하는데는 시간이 별로 안 걸렸는데, 구현을 이중 딕셔너리로 하고싶어서 고집부리다가 구현하는 데 시간을 많이 써버린...
=> [BOJ] 1969_DNA / 실버4 / 85분 / O

week10/BOJ_2503/숫자 야구_양승혜.py
- 백준 2503-숫자 야구
- 구현
- 조건에 맞지 않는 케이스들을 지워나가고, 남은 케이스들의 개수를 세는 방식으로 문제를 풀었습니다.
- 다만 케이스를 검증하기위해 케이스들의 인덱스를 도는 for loop에서 제가 제외한 케이스 만큼의 수를 제외해야했습니다.
- 계속 인덱스 에러가나서... 지운 케이스들의 개수만큼 i에서 빼는 코드를 다른 풀이를 살짝 참고하였습니다..!!(여기서 시간을 많이 잡아먹..)
=> [BOJ] 2503_숫자야구 / 실버3 / 135분 / O

week10/BOJ_2961/도영이가 만든 맛있는 음식_양승혜.py
- 백준 2961-도영이가 만든 맛있는 음식
- 구현
- 신맛, 단맛을 따로 리스트에 저장하고,
- 가능한 경우의 수를 combinations로 뽑아낸다
- 가능한 경우의 수를 for문으로 돌며 신맛과 단맛의 차이에 대한 절대값을 list에 저장하고, 가장 작은 값을 도출한다.
=> [BOJ] 2961 도영이가 만든 맛있는 음식 / 실버2 / 60분 / O

week10/BOJ_2615/오목_양승혜.py
- 백준 2616-오목
- 구현
- 오른쪽, 아래, 대각선 오른쪽 아래, 대각선 오른쪽 위 (가장 왼쪽에 있는 바둑알을 추출해내야하기 때문)를 돌며 검증해나가는 방식으로 풀었습니다.
- 육목을 체크할 때, 첫 바둑알의 앞에 같은 돌이 있는지, 가장 뒤 바둑알의 뒤에 같은 돌이 있는지 확인하여 육목인지를 가려냈습니다.
=> [BOJ] 2615 오목 / 실버1 / 80분 / O

week10/BOJ_2503/숫자 야구_최재선.js
- 백준 2503-숫자 야구
- 구현
- 모든 가능한 숫자들 buckets 저장
- 문제에 주어진 조건에 해당하는 숫자가 아닌 것 buckets에서 삭제
=> [BOJ] 2503 숫자 야구 / 실버3 / 10분 / O

week10/BOJ_15661/링크와 스타트_최재선.js
- 백준 15661-링크와 스타트
- bitwise
- 가능한 링크 조합을 2진수의 합으로 배열에 key-value 쌍으로 저장
- 모든 경우의 수부터 시작하여 (ex, 11111) 1씩 빼가면서 모든 경우에 대한 차이 값 순회
- 가장 작은 값 출력
=> [BOJ] 15661 링크와 스타트 / 골드5 / 15분 / O

week10/BOJ_14500/테트로미노_최재선.js
- 백준 14500-테트로미노
- 구현
- 2x2, 3x2, 2x3, 1x4, 4x1 조각의 압축 board 생성
- 2x3, 3x2 board에서는 끊어지지 않도록 2개의 제일 작은 수 선정해서 sum에서 빼기
- 해당 보드들의 최솟값 출력
=> [BOJ] 14500 테트로미노 / 골드4 / 25분 / O

week10/BOJ_2615/오목_최재선.js
- 백준 2615-오목
- 구현
- board 순회하며 연속된 방향으로 5개 이상 나타나는 곳 탐색
=> [BOJ] 2615 오목 / 실버1 / 15분 / O

week10/BOJ_1969/DNA_최재선.js
- 백준 1969-DNA
- 구현
- matrix를 세로로 순회하여 가장 많이 나온 알파벳 count 저장
- count 토대로 차이 계산 후 합산 및 알파벳 저장
=> [BOJ] 1969 DNA / 실버4 / 10분 / O

 week11/BOJ_1205/등수 구힉_홍지훈.py
- 백준 1205-등수 구하기
`구현`, `이진탐색`
- 이진탐색을 사용해 타겟이 되는 점수의 left 와 right 에 해당하는 인덱스가 어디인지 구했습니다.
- 이진탐색을 활용하기 위해 bisect 의 bisect_left, bisect_right 를 사용했고 reverse 를 시켜 정렬해주었습니다.
> 아이고.. 실버4인데도 너무 쉬운 문제를 선정했었네요.. 이게 참 문제 고르는게 어렵네요ㅜ
=> [BOJ] 1205_등수 구하기 / 실버4 / 15분 / O

 week11/BOJ_2607/비슷한 단어_홍지훈.py
- 백준 2607-비슷한 단어
`구현`
1. 같은 구성일때, 비슷한 단어일때의 경우로 나누어 코드를 구성했습니다.
2. 첫 번째 단어를 compare, 두번째 이후 단어들을 word 라고 이름을 붙이고 for 문을 돌릴때
3. 1) word 의 글자수가 compare 보다 1 작을 경우 문자를 더하기
- AABB, ABB
- AABBC, AABB
4. 2) word 의 글자수와 compare 가 같을 때
- 같은 구성일때 / 한 문자 교체
- AAAB, AAAC 
- AAAB, ABBA
5. 3) word 의 글자수가 compare 보다 1 클때 문자 빼기
- AAAB, AAAAB
- AAAB, AAABC
=> [BOJ] 2607_비슷한 단어 / 실버2 / 120분 / O

 week11/BOJ_1138/한줄로서기_r김윤설.java
- 백준 1138-한 줄로 서기
`구현`
바깥쪽 반복문으로 사람을 받고 안쪽 반복문에서 해당 자리를 방문하지 않고  나보다 큰 사람의 수 'p' 자리를 남겨두고 
나의 자리가 되면 방문 처리를 했습니다.
=> [BOJ]1138_한 줄로 서기/실버2/45분/X

 week11/BOJ_1205/등수구하기_김윤설.java
- 백준 1205-등수 구하기
`구현`
자바로 코딩테스트를 처음 풀어봐서 정답을 참고해서 풀었습니다.
n과p가 같고 기존 랭킹리스트보다 새로운 점수가 작거나 같으면 -1 출력
그렇지 않다면 반복문을 돌려 정답을 출력했습니다.
=> [BOJ]1205_등수구하기/실버4/30분/X

 week11/BOJ_9081/단어 맞추기_홍지훈.py
- 백준 9081-단어 맞추기
`조합론`, `구현`
```py
import sys
input = sys.stdin.readline
from itertools import permutations
T = int(input().rstrip()) # T : 테스트 케이스의 개수 1 ~ 10
for i in range(T):
word = input().rstrip() # word : 100자 이내 연속된 알패벳으로 구성된 단어
result = list(permutations(list(word), len(word)))
result = [''.join(list(tuple)) for tuple in result]
result = list(set(result))
result = sorted(result)
if result.index(word) < len(result) - 1:
print(result[result.index(word) + 1])
else:
print(word)
```
처음에 위와 같이 permutation 을 사용하니 예제는 통과되는데 공간복잡도가 높게 나와서 다음 풀이를 찾아봤습니다.
```py
def next_permutation(s):
i = len(s) - 1
while i > 0 and s[i - 1] >= s[i]: # i : 리스트를 뒤에서부터 탐색하며 현재 원소가 바로 뒤의 원소보다 작은 첫 번째 인덱스
i -= 1
if i == 0:
return s
j = len(s) - 1 # j : i 이전중 i - 1 보다 작거나 같은 첫 번째 원소
while s[j] <= s[i - 1]:
j -= 1 …
```
=> [BOJ] 9081_단어 맞추기 / 실버1 / 30분 / O

 week11/BOJ_1138/한 줄로 서기_홍지훈.py
- 백준 1138-한 줄로 서기
`구현`
- 먼저 사람의 수 N, 왼쪽에 자신보다 키가 큰 사람의 수에 대한 정보 배열 info, 결과적으로 줄을 서게 된 순서를 담은 result 생성
- 가정으로 info 의 숫자가 1번 사람, 2번 사람 ... 이 줄을 서게 될 인덱스와 같다고 가정했습니다. 이에 따라 result 에 info 의 값을 인덱스로 할때 result 가 0 인지 아닌지에 따라 조건문을 분기해줬습니다.
- 만약 result 가 비워져 있었다면 내 앞으로 채워진 것이 없을때와 있을때의 경우로 나눠 코드를 구성했습니다.
그 외에 처음부터 result 가 채워져 있었을 경우에 대한 코드를 따로 구성했습니다.
=> [BOJ] 1138_한 줄로 서기 / 실버2 / 60분 / O

 week11/PSG_순위검색/순위검색_최재선.js
- 프로그래머스 Lv2-순위 검색
- 구현
- 이분 탐색
- 데이터들을 각 쿼리에 해당하는 Obj 객체에 저장하여 필요한 arr을 탐색 후, score만 이분 탐색
=> [PGS] 순위 검색 / Lv2 / 30분 / O

 week11/BOJ_9081/단어 맞추기.js
- 백준 2607-단어 맞추기
- 힙
- 구현
- 뒷 단어부터 검색하여, charCode가 작아지는 단어가 오는 index를 검사 후, 검사된 단어 중 가장 작은 charCode를 가지는 단어부터 차례로 배치
=> [BOJ] 2607 단어 맞추기 / 실버1 / 30분 / O

 week11/BOJ_2636/치즈_최재선.js
- 백준 2636-치즈
- BFS
- 구현
- (0, 0) 부터 시작하여 bfs로 주변을 탐색 후, 1이 만나는 지점을 탐색 후 저장 및 종료
=> [BOJ] 2636 치즈 / 골드4 / 30분 / O

 week11/BOJ_2607/비슷한 단어_최재선.js
- 백준 2607-비슷한 단어
- 구현
- 2개 이상의 다른 알파벳 카운트가 날 시, 다른 단어로 간주하여 구현
=> [BOJ] 2607 비슷한 단어 / 실버2 / 10분 / O

 week11/BOJ_1138/한 줄로 서기.js
- 백준 1138-한 줄로 서기
- 구현
- Union Find
- 첫번째 순서부터 가고자 하는 index를 uf로 탐색 후 위치
=> [BOJ] 1138 한 줄로 서기 / 실버2 / 10분 / O

 week11/BOJ_1205/등수 구하기_최재선.js
- 백준 1205-등수 구하기
- 구현
- 이진 탐색
- 내 스크어를 넣고 정렬한 후, 이진 탐색을 통해 점수가 범위에서 벗어나는지 체크
=> [BOJ] 1205 등수 구하기 / 실버4 / 15분 / O

week12/BOJ_9655/돌 게임_홍지훈.py
- 백준 9655-돌 게임
`다이나믹 프로그래밍`
> dp 에 대해 더 익숙해지면 좋겠다는 생각으로 좀 쉬운 문제를 배정했습니다.. 
- 사실 홀수면 상근, 짝수면 창영이긴 합니다.. 그래도 dp 로 푸는 연습을 하기 위해 dp 방식으로 다시 풀어봤습니다.
- 게임이 이루어진 횟수에 따라 상근이 이기는지, 창영이 이기는지 결정됩니다. 
- 따라서 memo[n] 는 입력한 수 N 이 n 일때 이뤄진 게임의 수를 의미합니다.
- memo[n] 은 1 또는 3개의 돌을 가져갈 수 있으니 `min(dp(n-1) + 1, dp(n - 3) + 1)` 로 갱신합니다.
=> [BOJ] 9655_돌 게임 / 실버5 / 15분 / O

week12/BOJ_1463/1로 만들기_홍지훈.py
- 백준 1463-1로 만들기
`다이나믹 프로그래밍`
- top down 방식으로 풀이를 했을때 recurssion error 가 발생해서 bottom up 방식의 풀이로 바꿔 풀었습니다.
```py
memo = {}
memo[1] = 0
def dp(n):
for i in range(1, n):
memo[i + 1] = min(memo.get(i + 1, N), memo[i] + 1)
memo[i * 2] = min(memo.get(i * 2 , N), memo.get(i * 2 - 1, N) + 1, memo[i] + 1)
memo[i * 3] = min(memo.get(i * 3, N), memo.get(i * 3 - 1, N) + 1,  memo[i] + 1)
return memo[n]
print(dp(N))
```
- bottom up 방식이라 1 부터 시작해서 memo 를 채워나갑니다.
- 이때 1을 증가할때, 2를 곱할때, 3을 곱할때의 memo 를 갱신합니다.
- memo[n] 은 세가지 연산을 적절히 사용해 1을 만드는데 걸리는 횟수를 의미합니다.
- 각 연산에서 min 을 통해 원래 그 위치에서 1을 만드는데 걸리는 횟수, 바로 1 인덱스 아래에서 1을 증가시켰을때의 수, 곱하기 전에서 1을 증가시켰을 때의 수 들을 비교해 최소값으로 갱신합니다.
> `dictionary.get(key, option)` 에서 option 을 처음 써봤는데 두번째 인자를 전달하면 해당 키에 값이 존재하지 않는다면 N 을 할당하는 기능을 해줍니다. 처음엔 bottom up 방식이라 불필요하게 3N 까지 범위를 …
=> [BOJ] 1463_1로 만들기 / 실버3 / 50분 / O

week12/BOJ_11055/가장 큰 증가하는 부분 수열_홍지훈.py
- 백준 11055-가장 큰 증가하는 부분 수열
`다이나믹 프로그래밍`
- 먼저 nums[i] 를 마지막 원소로 가질 때 가장 긴 증가하는 부분 수열의 합을 저장할 dp 라는 배열을 생성합니다.
- 그러고 nums 를 순회하면서 각 인덱스를 end, 앞에서부터 start 를 end 까지 갱신해가며 
- nums[end] > nums[start] 를 만족할 때 dp[end] 를 갱신하도록 했고,
- end 와 start 가 같아졌어도 아직 초기화한 값 0 을 dp[end] 가 갖고 있다면 
- 현재 값 nums[end] 로 갱신하도록 했습니다.
https://leetcode.com/problems/longest-increasing-subsequence/description/
리트코드의 문제중 가장 긴 증가하는 부분 수열의 길이를 구하라는 문제입니다. 참고할만해서 공유해요~
=> [BOJ] 11055_가장 큰 증가하는 부분 수열 / 실버2 / 30분 / O

week12/BOJ_9251/LCS_홍지훈.py
- 백준 9251-LCS
`다이나믹 프로그래밍`
- `ABCDE`, `AOCKE` 라는 두 문자열이 있다고 가정해볼때 
- 두 문자열의 가장 긴 공통 부분 수열을 찾을때 가장 끝에 있는 문자가 같을 경우와 다를 경우를 나누어 LCS 를 구할 수 있다.
- 1. 만약 한쪽 끝에 존재하는 문자가 일치할 경우, 두 문자는 공통부분수열로 보고 두 문자를 제외한 나머지를 다시 dp
- 2. 만약 한쪽 끝에 존재하는 문자가 다를 경우 한쪽 문자를 제외 했을 때 더 긴 문자열을 나타내는 경우를 잡고 다시 dp
```py
for i in range(1, len(str1) + 1):
for j in range(1, len(str2) + 1):
if str1[i - 1] == str2[j - 1]:
dp[i][j] = dp[i- 1][j - 1] + 1 # 각 위치의 문자가 동일하면 각 문자열에서 해당 문자를 제외하고 다시 dp를 하고 구하고자 하는 공통 부분 수열 문자열의 길이는 1 증가
else:
dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]) # 만약 각 위치의 문자가 다르다면 해당 문자를 제외하고 다시 dp
```
- 본 코드에서 dp 는 2차원 dp 를 활용하는 것으로 dp[i][j] 는 i, j 까지 공통 부분 수열에 해당하는 문자열의 최대 길이를 나타낸다. 
- 그래서 초기값을 0으로 설정한다. ( 선택되지 않을 수 있다.)
```py
dp = [[0 for _ in range(len(str2) + 1)] for _ in range(len(str1) + 1)]
```
=> [BOJ] 9251_LCS / 골드5 / 80분 / X

week12 /BOJ_9655/돌 게임_양승혜.py
- 백준 9655 - 돌 게임
- dp
- 계속 값을 구하다보면 주어진 수가 홀수 일때 상근이, 짝수일 때 창영이가 이긴다.
=> [BOJ] 9655 돌 게임 / 실버5 / 5분 / O

week12/BOJ_1890/점프_양승혜.py
- 백준 1890-점프
- dp
- 0으로 채워진 dp 배열을 만든다
- dp배열의 첫 값을 1로 놓고, 보드를 오른쪽, 아래로 이동하며 인덱스가 range에 맞으면 dp배열에 값을 추가한다.
- 이 때, dp배열의 값이 1이고 보드의 값이 0이 아닐 때만 visit하게한다.
- 마지막 행, 열에 해당하는 값을 프린트한다.
=> [BOJ] 1890 점프 / 실버1 / 45분 / O

week12/BOJ_1463/1로 만들기_양승혜.py
- 백준 1463-1로 만들기
- dp
- 재귀 + dp
1. bottom up : 536ms
- for 문을 돌며 일단 1을 뺐을 때의 경우의 수를 dp배열에 저장하고,
- 만약 3이나 2로 나누어진다면, **2나 3으로 나눈 숫자에 해당하는 dp인덱스의 값에 1을 더한 값**과 **본래의 dp인덱스에 해당하는 값**과 비교하여 최솟값을 구한다.
2. top down : 40ms
- 딕셔너리 형태로 dp 를 만들고,
- 함수를 만든다 : 재귀함수
- 만약 인수로 전달되는 값이 dp의 키 값에 포함된다면, 해당 키 값에 해당하는 value값을 리턴하고 종료
- 만약 인수로 전달되는 값이 3, 2 모든 숫자로 나누어진다면, (인수를 3으로 나눈 몫에 해당하는 값의 결과 + 1한 값, 인수를 2로 나눈 몫에 해당하는 값의 결과 + 1 한값) 중 작은 수를 dp 딕셔너리에 넣는다.
- 3 또는 2로 나누어 지는 수는, '인수 -1' 한 값과 '인수 // 2(또는 3)' 한 값에 +1 한 값 중 최솟값을 dp 딕셔너리에 넣는다.
- dp[인수]값을 출력한다.
top down 형식으로 짠 코드의 속도가 훨씬 빠르네요!! 딕셔너리 자료형이어서 그럴까요..??
=> [BOJ] 1463 1로 만들기 / 실버3 / 35분 / O

week12/BOJ_11055/가장 큰 증가하는 부분 수열_양승혜.py
- 백준 11055-가장 큰 증가하는 부분 수열
- dp
- input 값을 받는 array, array 값을 deep copy한 배열인 dp를 만든다.
- 2중 for 문을 돌면서 뒤의 값이 앞의 값보다 클 때만 dp 배열의 값을 갱신한다.
- max(원본 배열[i] + dp[j], dp[i])의 값이 dp[i]의 값이 된다.
- dp 배열 중 가장 큰 값을 출력한다.
=> [BOJ] 11055_가장 큰 증가하는 부분 수열 / 실버2 / 25분 / O

week12/PGS_메뉴 리뉴얼/메뉴 리뉴얼_양승혜.py
- 프로그래머스 - 메뉴 리뉴얼
- 조합
- 코스의 개수를 돌면서 combinations를 활용해서 해당 코스 개수에 알맞는 메뉴의 가지수를 전부 구한다.
- Counter를 활용해서 메뉴의 가지수를 구하고, most_common()을 사용해서 정렬한다.
- 가장 큰 값, 1개 이상 등장한 값만 answer 리스트에 추가한다.
=> [PGS] 메뉴 리뉴얼 / Lv2 / 60분 / O

week12/BOJ_1463/1로 만들기_이서연.py, week12/BOJ_9655/돌 게임_이서연.py
- 백준 1463-1로 만들기
다이나믹 프로그래밍
- d : 각 숫자를 1로 만들기 위해 필요한 연산 횟수를 저장할 리스트 
- 1부터 입력 받은 숫자까지 반복하며 최소 연산 횟수 저장
- d[i - 1] + 1 : 1을 뺀 경우
- d[i // 2] + 1 : 2로 나눈 경우
- d[i // 3] + 1 : 3으로 나눈 경우
- 💥 주의 : 위에서의 +1은 숫자 변경 X 연산 횟수 증가를 위한 +1 O
=> [BOJ] 1463_1로 만들기 / 실버3 / 45분 / X

week11/BOJ_1138/한 줄로 서기.js, week11/BOJ_1205/등수 구하기_최재선.js, week11/BOJ_2607/비슷한 단어_최재선.js, week11/BOJ_2636/치즈_최재선.js, week11/BOJ_9081/단어 맞추기_최재선.js, week11/PSG_순위검색/순위검색_최재선.js, week12/BOJ_11055/가장 큰 증가하는 부분 수열_이서연.py, week12/BOJ_1463/1로 만들기_이서연.py, week12/BOJ_9655/돌 게임_이서연.py
- 백준 11055-가장 큰 증가하는 부분 수열
다이나믹 프로그래밍
- 가장 작은 부분 집합은 자기 자신만을 원소로 갖는 부분 집합이므로 d에 list 값 복사(깊은 복사)
- for문을 돌며 list에서 target 값 앞에 위치해있음 && 그 원소가 target 값보다 작은 경우  
→ target 값의 가장 큰 부분 수열의 합(d[i])과 이전 원소의 가장 큰 부분 수열의 합과 target 값을 더한 값(d[j] + list[i]) 중, 더 큰 값으로 업데이트
=> [BOJ] 11055_가장 큰 증가하는 부분 수열 / 실버2 / 45분 / X

week11/BOJ_1138/한 줄로 서기.js, week11/BOJ_1205/등수 구하기_최재선.js, week11/BOJ_2607/비슷한 단어_최재선.js, week11/BOJ_2636/치즈_최재선.js, week11/BOJ_9081/단어 맞추기_최재선.js, week11/PSG_순위검색/순위검색_최재선.js, week12/BOJ_11055/가장 큰 증가하는 부분 수열_이서연.py, week12/BOJ_1463/1로 만들기_이서연.py, week12/BOJ_1890/점프_이서연.py, week12/BOJ_9655/돌 게임_이서연.py
- 백준 1890-점프
다이나믹 프로그래밍
- game[] : 게임의 map
- d[] : 경로 횟수
- 왼쪽 맨 위의 좌표는 무조건 방문할 수밖에 없으므로 반복문을 돌기 전에 경로 횟수를 1로 설정(d[0][0] = 1)
- size * size만큼 반복문 돌기
- 현재 좌표가 오른쪽 맨 아래라면, 해당 위치의 경로 횟수를 출력 후, 반복문 break
- 현재 좌표가 규칙에 맞게 접근 가능한 위치(d[i][j] != 0) && 해당 숫자만큼 오른쪽으로 이동 가능(j + game[i][j] < size)
→ 이동 후, 해당 좌표의 경로 횟수 업데이트
(이동한 좌표의 경로 횟수 + 이전 좌표의 경로 횟수(d[i][j + game[i][j]] += d[i][j]))
- 현재 좌표가 규칙에 맞게 접근 가능한 위치(d[i][j] != 0) && 해당 숫자만큼 아래쪽으로 이동 가능(i + game[i][j] < size)
→ 이동 후, 해당 좌표의 경로 횟수 업데이트
(이동한 좌표의 경로 횟수 + 이전 좌표의 경로 횟수(d[i + game[i][j]][j] += d[i][j]]))
=> [BOJ] 1890_점프 / 실버1 / 45분 / X

week12/BOJ_11055/가장 큰 증가하는 부분 수열_이서연.py, week12/BOJ_1463/1로 만들기_이서연.py, week12/BOJ_1890/점프_이서연.py, week12/BOJ_9251/LCS_이서연.py, week12/BOJ_9655/돌 게임_이서연.py
- 백준 9251-LCS
다이나믹 프로그래밍
- d : 두 번째 문자열에 대해 접근 횟수를 저장할 리스트
- value : 누적값
- 누적값(value)이 해당 글자의 접근 횟수(d[j])보다 작으면, 누적값 update
- 누적값이 해당 글자의 접근 횟수보다 크거나 같고, 1번 문자열과 2번 문자열의 문자가 같으면, 해당 글자의 접근 횟수 증가(d[j] = value + 1)
=> [BOJ] 9251_LCS / 골드5 / 45분 / X

week12/BOJ_11055/가장 큰 증가하는 부분 수열_이서연.py, week12/BOJ_1463/1로 만들기_이서연.py, week12/BOJ_18427/함께 블록 쌓기_이서연.py, week12/BOJ_1890/점프_이서연.py, week12/BOJ_9251/LCS_이서연.py, week12/BOJ_9655/돌 게임_이서연.py
- 백준 18427-함께 블록 쌓기
다이나믹 프로그래밍
- d : 블록을 이용하여 0부터 h까지 만들 수 있는 경우의 수를 저장한 2차원 배열
- 합이 0인 경우는 무조건 1가지이므로 d의 [x][0]은 항상 1
- 학생의 수만큼 반복(i)
- 이전 학생의 누적값 배열(d[i - 1])을 가져온 후, 그에 대해 추가로 경우의 수를 더함
- j : 블록을 더해서 만들고자 하는 값
- d[i][j] : 현재 block 값을 만드는 경우의 수
- d[i - 1][j - b] : j를 만들기 위해 더해야 하는 수를 만드는 경우의 수(j - block 값을 만드는 경우의 수)
=> [BOJ] 18427_함께 블록 쌓기 / 골드4 / 45분 / X

week12/PGS_메뉴 리뉴얼/메뉴 리뉴얼_최재선.js
- 프로그래머스 2607-메뉴 리뉴얼
- bitMasking
- dfs
- 메뉴들의 알파벳 조합을 Bit로 저장 후, 가능한 모든 조합을 Bit의 합으로 저장하고, 순회하여 가장 count가 많은 조합 return
=> [PGS] 메뉴 리뉴얼 / Lv2 / 15분 / O

week12/BOJ_1463/1로 만들기_최재선.js
- 백준 1484-1로 만들기
- Queue
- 2 또는 3으로 나누어 떨어지는 경우와 1을 뺀 경우의 결과값에 해당 값을 Queue에 등록
- 순차적으로 진행하며 1이 나올 때, 진행한 횟수 return
=> [BOJ] 1484 1로 만들기 / 실버3 / 10분 / O

week12/BOJ_11055/가장 큰 증가하는 부분 수열_최재선.js
- 백준 11055-가장 큰 증가하는 부분 수열
- dp
- 특정 값으로 마지막에 끝났을 때 해당하는 수의 합을 저장하는 DP 선언
- 특정 DP 지점에 왔을 때, 합이 DP에 해당하는 합보다 크다면 DP 업데이트
- 유효한 값을 가지는 DP Index Set객체에 저장
=> [BOJ] 11055 가장 큰 증가하는 부분 수열 / 실버2 / 15분 / O

week12/BOJ_1890/점프_최재선.js
- 백준 1890-점프
- dp
- 특정 지점에 올 수 있는 경우의 수를 저장할 DP 배열 선언
- 점프 조건에 따라 DP 업데이트
=> [BOJ] 1890 점프 / 실버1 / 15분 / O

week12/BOJ_9251/LCS_최재선.js
- 백준 9251-LCS
- dp
- 부분 수열을 저장할 DP 선언
- DP를 세로 순회할 때, 해당하는 배열의 특정 인덱스의 값을 토대로, 다음 배열의 해당 인덱스와 같은 위치의 값을 업데이트
- 가로로 순회 시, 나왔던 값 중 가장 큰 값(max)를 업데이트하며 DP에 반영
=> [BOJ] 9251 LCS / 골드5 / 25분 / O

week12/BOJ_18427/함께 블록 쌓기.js
- 백준 18427-함꼐 블록 쌓기
- dp
- 쌓아야 할 블록의 높이를 기반으로 DP 배열 초기화
- 특정 높이의 블록을 만들 수 있는 개수를 DP 배열에 업데이트
=> [BOJ] 18427 함꼐 블록 쌓기 / 골드5 / 15분 / O

week12/BOJ_9251/LCS_김선진.py
- 백준 9251-LCS
동적 계획법
s1과 s2에 가장 최근에 추가된 글자가 서로 같을 때, matrix[i][j] = matrix[i-1][j-1]+1 길이는 (두 글자가 추가되기 전 가장 큰 길이 + 1)이 된다.
s1과 s2에 가장 최근에 추가된 글자가 서로 다르다면, matrix[i][j] = max(matrix[i][j-1], matrix[i-1][j]) 기존에 주어진 문자열로 만들 수 있던 최대 길이를 갖게 된다.
[LCS 문제 풀이](https://suri78.tistory.com/11)
=> [BOJ] 9251_LCS / 골드 5 / 60분 / X

week13/BOJ_1158/요세푸스 문제_홍지훈.py
- 백준 1158-요세푸스 문제
`구현`, `덱`
- deque 의 경우 rotate 라는 메서드가 있어서 K 번째 사람이면 rotate(- (K - 1)) 만큼 해줬을 때 0번째 인덱스의 사람이 제거해줄 사람과 같습니다.
- 그래서 rotate 이후 popleft 하는 식으로 풀이했습니다.
=> [BOJ] 1158_요세푸스 문제 / 실버4 / 10분 / O

week13/BOJ_1063/킹_홍지훈.py
- 백준 1063-킹
`구현`
- dir 라고 하는 맵을 생성해서 키로 움직일 방향을 문자열로 넣으면 행, 열 방향으로 얼만큼 이동했는지를 value 로 나타내도록 했습니다.
```py
dir = {'R': [0, 1], 'L': [0, -1], 'B': [-1, 0], 'T': [1, 0], 
'RT': [1, 1], 'LT': [1, -1], 'RB': [-1, 1], 'LB': [-1, -1]}
```
- 체스판 board 를 만들어 0행부터 A8 B8 ... 7행까지 A0 B0 ... 를 갖도록 하는 2차원 행렬을 만들었습니다.
```py
board = [[chr(j) + str(i) for j in range(65, 73)] for i in range(8, 0, -1)]
```
- A0 => row, col 을 반환하는 find_loc 과
- row, col => A0 을 반환하는 find_coordinate 함수를 생성했습니다.
```py
def find_loc(coordinate):
col = ord(coordinate[0]) - 65
row = int(coordinate[1]) - 1
return [row, col]
def find_coordinate(row, col):
return chr(col + 65) + str(row + 1)
```
- 위의 두 함수를 통해 입력받은 초기 돌과 킹의 row, col 을 구하여 킹의 움직임과 돌의 움직임이 각각 유효시 새 위치로 업데이트 시켜주고
- 업데이트 된 row, col 을 find_coordinate 를 통해 다시 A0 같은 형태로 …
=> [BOJ] 1063_킹 / 실버3 / 30분 / O

week13/BOJ_21610/마법사 상어와 비바라기_홍지훈.py
- 백준 21610-마법사 상어와 비바라기
`구현`
- 각 단계별로 풀이를 했습니다.
- 1단계에서 구름이 di 방향으로 si 칸만큼 이동하기 위해 update 라는 메서드를 만들었습니다.
- 2단계에서 물의 양을 1 증가 ( 단, 방문 여부 체크 )
```py
def update(next: int) -> int:
return (next - 1) % N + 1
def move(row: int, col: int, dr: int, dc: int):
nr, nc = update(row + dr), update(col + dc) 
if 1 <= nr <= N and 1 <= nc <= N:
grid[nr][nc] += 1
moved_clouds.append([nr, nc])
visited[nr][nc] = True
```
- 3단계에서 구름을 모두 제거
- 4단계에서 물복사버그 반영
- 5단계에서 새로 구름을 생성
=> [BOJ] 21610_마법사 상어와 비바라기 / 골드5 / 120분 / O

week13/BOJ_20056/마법사 상어와 파이어볼_홍지훈.py
- 백준 20056-마법사 상어와 파이어볼
`구현`
- k 번 이동할 수 있습니다
- 파이어볼의 정보는 info 라는 배열에 담았습니다.
- 매번 이동할 때마다 info 에 저장되어 있는 파이어볼을 1단계, 위치를 업데이트하고 기존 파이어볼 정보를 삭제합니다.
- 2단계, 만약 2개 이상 파이어볼이 존재한다면
- 해당 셀의 파이어볼 질량 더하기
- 해당 셀의 파이어볼 속력 더하기
- 해당 셀의 파이어볼들의 방향이 모두 홀수 혹은 짝수인지 여부 확인하기 - all_even_or_odd 메서드 생성
- 생성된 새로운 파이어볼의 질량 구하기 -> 0이라면 새로 생성된 파이어볼은 소멸
- 새 파이어볼의 속력 구하기
- 새 파이어볼의 방향 구하기 를 반영한다.
- 위의 결과 업데이트된 파이어볼의 정보 info 를 토대로 K 번 반복한다.
=> [BOJ] 20056_마법사 상어와 파이어볼 / 골드4 / 100분 / O

.gitignore, week13/BOJ_1158/요세푸스 문제_양승혜.py
- 백준 1158-요세푸스 문제
- 큐, 구현
- deque를 사용하여 풀이
- 입력값을 받은 큐를 K-1 번만큼 popleft()하고 뒤로 다시 append()한 뒤, 가장 앞의 값을 answer 배열에 append한다.
- answer 배열을 string으로 변환하여 대괄호를 <>로 replace 하여 출력한다.
=> [BOJ] 1158 요세푸스 문제 / 실버4 / 20분 / O

week13/BOJ_1063/킹_양승혜.py
- 백준 1063-킹
- 구현
- 열을 알파벳 A~H까지 리스트에 채운다(인덱스 활용하기 위해)
- 움직이는 방향을 딕셔너리로 저장한다.
- for in loop를 돌면서 조건에 맞으면 움직인다. 돌과 좌표가 같으면 돌도 움직여준다. 
- 만약 조건에 맞지 않으면 돌과 킹을 원래상태로 되돌리고,
- 문제에 주어진 조건대로 print한다
=> [BOJ] 1063_킹 / 실버3 / 60분 / O

week13/BOJ_21611/마법사 상어와 블리자드_최재선.js
- 백준 21611-마법사 상어와 블리자드
- 구현
- 2차원 배열을 상어가 가는 길을 따라 1차원 배열로 재정렬
- 점화식을 통해 4가지 방향에 해당하는 index 저장
- 문제의 조건에 따라 queue 형태로 차례차례 3개 이상이 카운팅 된 곳을 빼고 합치기
=> [BOJ] 21611 마법사 상어와 블리자드 / 골드1 / 40분 / O

week13/BOJ_1158/요세푸스 문제_최재선.js
- 백준 1158-요세푸스 문제
- LinkedList
- 원탁을 LinkedList로 정렬 후, 문제 조건에 따라 LinkedNode 제거
=> [BOJ] 1158 요세푸스 문제 / 실버4 / 10분 / O

week13/BOJ_1063/킹_최재선.js
=> [BOJ] 1063 킹 / 실버3 / 15분 / O

week13/BOJ_21610/마법사 상어와 비바라기_최재선.js
=> [BOJ] 21610 마법사 상어와 비바라기 / 골드5 / 25분 / O

week13/BOJ_13335/트럭_최재선.js
=> [BOJ] 13335 트럭 / 실버1 / 15분 / O

week14/BOJ_14594/동방 프로젝트 (Small)_홍지훈.py
- 백준 14594-동방 프로젝트 (Small)
`구현`, `시뮬레이션`
- 이미 벽이 허물어져있으면 무시하고 다음 방의 벽을 허물라고 하는 부분이 만약 2개의 벽을 허물어야 하는데 그중 1개의 벽이 이미 허물어져 있었다면 추가로 1개의 벽을 허물라는 소리로 이해했으나 빌런들이 허당해서 이미 허물어져 있는 벽은 무시하고 기존에 허물려고 했던 범위 내에서만 벽을 부수면 된다는 사실을 알게 되었습니다
=> [BOJ] 14594_동방 프로젝트 (Small) / 실버4 / 10분 / O

week14/BOJ_8911/거북이_홍지훈.py
- 백준 8911-거북이
`구현`, `시뮬레이션`
- 처음엔 좌측 상단과 우측 하단 두 포인트를 업데이트하는 것을 반복하며 두 지점 사이 직사각형의 넓이를 구했는데 좌측 하단, 우측 상단에 max point 가 존재할 경우 제대로 넓이를 구하지 못하기에 max row, min row, max col, min col 을 업데이트해서 그 사이 넓이를 구하는 방식으로 풀었습니다.
=> [BOJ] 8911_거북이 / 실버3 / 20분 / O

week14/BOJ_5212/지구 온난화_홍지훈.py
- 백준 5212-지구 온난화
`구현`, `시뮬레이션`
1. 완전탐색으로 grid 중 땅인 곳 탐색
2. 땅 주변 바다의 수 카운트 (grid 영역 바깥이면 바다) 해서 3 이상이면 50 년 뒤엔 가라앉도록 코드 작성
3. 새로 생성한 grid 를 완전 탐색하여 maxC, maxR, minC, minR 를 구합니다.
4. 해당 범위 내를 출력합니다.
=> [BOJ] 5212_지구 온난화 / 실버2 / 60분 / O

week14/BOJ_21609/상어 중학교_홍지훈.py
- 백준 21609-상어 중학교
`구현`, `시뮬레이션`
- 블록 그룹 찾기는 BFS 로 풀이합니다. 이때 무지개 블록일때 큐에 추가하고 무지개 블록 리스트에 더하며 
- 무지개 블록이 아닌 일반 블록일때도 큐에 추가하고 일반 블록 리스트에 추가합니다.
- 블록 그룹을 찾았으면  해당 그룹들중 정렬을 통해 가장 큰 블록그룹을 찾습니다.
- 이때 가장 큰 블록그룹을 찾을 때 정렬 기준이 블록 그룹의 수 -> 무지개 블록의 수 -> 기준블록의 행 -> 기준 블록의 열 순서이니 그룹에 해당 정보들을 넣어둡니다.
- 선정된 블록그룹을 제거하고 접수를 갱신한 뒤 중력을 적용합니다.
- 90 도 반시계방향 회전후 다시 중력을 적용하는 과정을 블록 그룹이 없어질 때까지 반복합니다.
https://velog.io/@qmflf556/algorithm-matrix-transpose-reverse-rotate#matrix--90-%EB%8F%84-%ED%9A%8C%EC%A0%84
transpose, reverse, 90도 회전, -90도 회전 (이번에 추가) 에 대한 파이썬 코드들을 정리해둔 블로그 페이지입니다. 
> 이 문제 삼성 SW 기출문제였네요.. 문제가 길긴 한데 깔끔한 구성으로 되어있는 것 같습니다.. 물론 시간내에 풀지는 못했지만 연습하다 보면 할만할 것 같아요
=> [BOJ] 21609_상어 중학교 / 골드 2 / 120분 / X

week13/BOJ_13335/트럭_이서연.py
- 백준 13335-트럭
큐
- bridge 배열에는 현재 다리 위에 올라간 truck의 무게가 저장됨
- 반복문을 돌 때마다 시간 +1
- 현재 다리 위에 올라간 truck의 무게(sum(bridge)) + 다리 위에 올라가기를 기다리고 있는 트럭(trucks[0])의 무게
→ 전체 하중보다 작으면 : trucks에서 첫 번째 요소를 pop하고 이를 bridge 배열의 마지막에 추가
→ 전체 하중보다 크면 : bridge 배열의 마지막에 0 추가(트럭이 올라가지 않음을 의미)
=> [BOJ] 13335 트럭 / 실버1 / 45분 / X

week13/BOJ_1158/요세푸스 문제_이서연.py, week13/BOJ_13335/트럭_이서연.py
- 백준 1158-요세푸스 문제
큐
- people : 사람들의 번호를 저장하고 있는 배열
- k번째에 해당하는 사람을 people에서 pop한 후, 이동하기 때문에 반복문을 돌 때마다 다음 인덱스로는 k - 1을 더함
- 인덱스 값이 배열 범위를 벗어날 경우, 배열의 길이로 % 연산을 하여 배열 앞부터 다시 접근할 수 있도록 함
=> [BOJ] 1158 요세푸스 문제 / 실버4 / 30분 / O

week13/BOJ_1063/킹_이서연.py
- 백준 1063-킹
구현
- alphabet 배열을 사용하여 입력받은 king과 돌의 위치를 숫자 형식(0, 0)으로 변환
- movings : 입력받은 움직임 번호에 따라 이동할 좌표를 저장한 딕셔너리
- 반복문을 돌며 king 위치 이동
- 이동한 king의 위치가 현재 돌의 위치와 동일하다면,
- 돌의 위치도 이동
- 만약, 돌이 체스판 범위를 벗어난다면, king 위치 원상복귀
=> [BOJ] 1063 킹 / 실버3 / 45분 / X

week13/BOJ_21610/마법사 상어와 비바라기_이서연.py
- 백준 21610-마법사 상어와 비바라기
구현
- king 문제처럼 움직이는 방향에 따라 좌표를 계산할 수 있도록 좌표값을 딕셔너리로 저장
- 현재 구름의 위치는 clouds 배열에 저장
- 이동한 구름의 위치는 moved_clouds 배열에 저장
- 모든 대각선 방향으로 이동할 때의 좌표값은 딕셔너리에서 2, 4, 6, 8에 해당하므로 구름이 이동한 후, moved_clouds 배열에 저장된 값에 대해 해당 위치를 모두 탐색
- 문제 조건에 따라 moved_clouds에 포함되지 않고 물의 양이 2인 경우, new_clouds 배열에 새로운 구름의 위치 저장
- 현재 구름 좌표값을 새로운 구름 좌표값으로 업데이트 후, 다시 반복 시작
- 시간 초과 문제를 해결하지 못했습니다...😂
=> [BOJ] 21610 마법사 상어와 비바라기 / 골드5 / 45분 / X

week14/BOJ_14594/동방 프로젝트 (Small)_이서연.py
- 백준 14594-동방 프로젝트 (Small)
구현
- rooms 배열에 방들 사이에 위치한 벽을 저장(양끝의 벽 제외)
- 벽이 존재하는 경우에는 1, 허물어진 경우에는 0으로 표시
- 행동을 할 때마다 해당 위치에 해당하는 rooms의 값을 1에서 0으로 변경
- 행동이 끝난 후, 최종 방의 개수 = 남은 벽의 개수의 합 + 1이므로 sum(rooms) + 1
=> [BOJ] 14594_동방 프로젝트 (Small) / 실버4 / 30분 / O

week14/BOJ_8911/거북이_이서연.py
- 백준 8911-거북이
구현
- 현재 거북이의 방향에 따라 F, B를 명령했을 때, 좌표 계산이 달라지므로 현재 방향을 cur_dir에 저장
- tx, ty는 현재 거북이가 위치한 좌표값
- top, bottom, left, right는 거북이가 이동했던 가장 상단, 하단, 좌측, 우측의 좌표값
- 명령이 F 또는 B이면(거북이가 움직인다면), move 함수를 통해 이동한 좌표값 계산
- if문을 통해 top, bottom, left, right 값 업데이트
- 명령이 끝나면, 무조건 top, bottom, left, right 값을 업데이트하는 방법도 가능
- 코드 라인 수가 줄어드는 대신에 시간이 늘어나 위의 방법이 아닌 별도의 if문을 돌도록 설정
- 명령이 L 또는 R이면, cur_dir의 값을 +1 또는 -1하여 업데이트
- cur_dir의 값은 directions 배열에 접근하기 위한 인덱스이므로 directions배열의 인덱스 범위인 0 <= cur_dir <= 3을 만족해야 함
- 따라서 업데이트한 cur_dir의 값이 양수라면 %4, 음수라면 %(-4) 연산을 진행하여 범위를 벗어나지 않도록 함
- 지나간 영역은 직사각형이므로 직사각형의 세로는 (top - bottom), 가로는 (right - left)
- 세로와 가로를 곱한 값을 print
=> [BOJ] 8911_거북이 / 실버3 / 45분 / O

week14/BOJ_5212/지구 온난화_이서연.py
- 백준 5212-지구 온난화
구현
- maps : 현재 지도, new_maps : 현재 지도
- cnt : 땅 주변에 위치한 바다의 개수
- 현재 지도가 땅일 때('X'), 4개 방향을 돌며 주변에 위치한 바다의 개수를 count
- 인접한 세 칸 이상이 바다라면, new_maps에서 해당 위치는 바다로 변경('.')
- maps의 요소 개수만큼 반복하며 new_maps 업데이트
- new_maps를 모두 그린 후, 섬의 개수에 맞게 지도의 크기를 작게 만드는 작업 진행
- new_maps의 요소 개수만큼 반복문을 돌며 땅이 위치한 최상단, 최하단, 가장 좌측, 가장 우측의 좌표값 업데이트 (top, bottom, left, right)
- top, bottom, left, right 값을 기준으로 직사각형 모양으로 new_maps를 출력하면, 50년 후의 지도 출력 가능
=> [BOJ] 5212_지구 온난화 / 실버2 / 45분 / O

week14/BOJ_1713/후보 추천하기_이서연.py
- 백준 1713-후보 추천하기
구현
- candidates : 사진틀에 게시된 학생 번호
- cnt : 사진틀에 게시된 해당 학생이 추천 받은 횟수
- candidates와 cnt의 인덱스 번호를 맞춰 candidates[0]의 학생이 추천받은 횟수를 cnt[0]에 저장
- 추천받은 학생이 이미 사진틀에 걸려 있다면, cnt 배열의 값 +1
- 추천받은 학생이 사진틀에 걸려있지 않고, 사진틀에 걸린 사진의 개수가 N보다 작다면, 해당 학생을 candidates 배열에 추가하고, cnt 배열의 값을 1로 설정
- 추천받은 학생이 사진틀에 걸려있지 않고, 사진틀에 걸린 사진의 개수가 N보다 크다면, 추천받은 횟수가 가장 적은 학생을 candidates 배열에서 pop하고, 새로운 학생을 append
- 마찬가지로 cnt에서 해당 idx에 해당하는 값을 pop한 후, 1 append
- 새롭게 추천받은 학생은 배열의 마지막 위치에 append하므로 가장 오래된 사진을 삭제한다는 조건은 별도로 체크할 필요 X
- 학생 번호를 증가하는 순서대로 출력한다는 조건에 따라 candidates를 sort 함수를 통해 오름차순 정렬 후 출력
=> [BOJ] 1713_후보 추천하기 / 실버1 / 45분 / X

week14/BOJ_16234/인구 이동_이서연.py
- 백준 16234-인구 이동
dfs
- flag가 true라면, 계속해서 반복하도록 while문 사용
- 중첩 for문을 통해 모든 땅에 대해 완전 탐색
- visited : 해당 나라를 방문했는지 여부를 저장
- open : 국경선을 연 나라의 좌표값을 저장
- 해당 나라를 방문한 적이 없다면, move 함수를 통해 dfs 실행
- move 함수
- 인자로 받은 좌표값에 위치한 나라를 방문했다고 표시
- 4개 방향에 대해 x, y 좌표값 업데이트
- 업데이트한 x, y 좌표가 N * N 범위를 벗어나지 않고, 해당 나라를 방문한 적이 없다면, 현재 위치한 나라의 인구 수와 인접한 나라의 인구 수를 비교
- 인구 수 차이가 L과 R 사이라면, open에 업데이트한 좌표값 추가
- 업데이트한 좌표값에 대해 move 함수 재호출
- 최종적으로 어떤 나라의 국경선을 열었는지에 대한 값을 가지고 있는 open return
- open의 길이가 1보다 크다면(국경을 연 나라가 존재한다면), 연합의 평균값으로 인구 수 업데이트
- 인구 이동이 한 번 발생하였으므로 cnt 값 1 증가
- 중첩 for문을 실행하였음에도 flag가 false라면, 이는 인구 이동이 없었음을 뜻하므로 break를 통해 while문 종료
- cnt 값 출력
=> [BOJ] 16234_인구 이동 / 골드 4 / 45분 / X

week14/BOJ_16234/인구 이동_최재선.js
=> [BOJ] 16234 인구 이동 / 골드4 / 15분 / O

week14/PGS_수식 최대화/수식 최대화_최재선.js
- 프로그래머스-수식 최대화
- 구현
- 백트래킹
- 백트래킹을 이용하여, 가능한 수식 조합을 완성한 후, 해당 수식 조합을 백트래킹을 이용하여 계산
[PGS] 수식 최대화 / lv2 / 20분 / O
=> [PGS] 수식 최대화 / lv2 / 20분 / O

week13/BOJ_21610/마법사 상어와 비바라기_최재선.js, week14/BOJ_21609/상어 중학교_최재선.js
- 백준 21610-상어 중학교
- 구현
- 시뮬레이션
- BlockGroup을 만드는 함수, 해당 그룹을 필터링 하는 함수, Stone을 제거하는 함수, 중력을 적용하는 함수, 시계 반대방향으로 돌리는 함수를 각각 나눠 구현한 후, 적용
=> [BOJ] 21609 상어 중학교 / 골드2 / 40분 / O

week14/BOJ_8911/거북이_문지영.py
- 백준 8911-거북이
구현, 시뮬레이션
*60분 제한을 걸었으나 해결하지 못하여 풀이를 찾아보고 코드를 작성하였습니다.*
1. direction을 0, 1, 2, 3 시계방향으로 지정
2. F, B의 경우 알파벳에 따라 좌표 이동
3. L, R의 경우 방향 바꿈
4. 최댓값들 구하고 넓이 구하기
=> [BOJ] 8911_거북이 / 실버3 / 60분 / X

week14/BOJ_14594/동방 프로젝트 (small)_문지영.py
- 백준 14594-동방 프로젝트 (small)
구현, 시뮬레이션
처음 시작점을 True로 지정하여 가장 왼쪽방을 신경쓰지 않도록 설정하였다.
=> [BOJ] 14594_동방 프로젝트 (Small) / 실버4 / 60분 / O

week14/BOJ_5212/지구 온난화_문지영.py
- 백준 5212-지구온난화
구현, 시뮬레이션
*완벽한 코드가 아닙니다.
50년 후 새롭게 Print하는 부분이 잘 동작하지 않는 것으로 예상됨 -> 코드 수정 필요
=> [BOJ] 5212_지구 온난화 / 실버2 / 60분 / X 

week15/BOJ_1012/유기농 배추_홍지훈.py
- 백준 1012-유기농 배추
`bfs`
- 배추가 심어져 있는 fields 먼저 만들고 배추가 심어져 있는 곳들의 방문 여부를 나타내는 visited 를 만들었습니다.
- 완전 탐색할때 배추가 심어져 있고 방문했다면 0을 반환하고 아직 방문한적이 없다면 해당 지점을 기준으로 유효한 상하좌우 방향에 bfs 를 반복하여 방문처리를 하며 1을 반환합니다.
- 반환된 0 또는 1을 합하면 연결되어 있는 배추 그룹의 수를 구할 수 있습니다.
=> [BOJ] 1012_유기농 배추 / 실버2 / 40분 / O

week15/BOJ_2206/벽 부수고 이동하기_홍지훈.py
- 백준 2206-벽 부수고 이동하기
`bfs`
- 방문 여부에 True, False 가 아닌 거리로 표시하며 3차원 배열을 사용하여 벽을 부쉈는지 아닌지 여부를 갱신합니다.
- 최종적으로 (N-1, M-1) 좌표의 visited 에 이동거리가 갱신되어 출력합니다.
=> [BOJ] 2206_벽 부수고 이동하기 / 골드3 / 120분 / X

week15/BOJ_16918/봄버맨_홍지훈.py
- 백준 16918-봄버맨
`bfs`
> 와.. 이거 한참 고민했는데 하다하다 안풀려서 다른분 풀이를 참고했습니다.
질문 게시판을 참고해보니 1초, 짝수, 1보다 클때 4로 나눈 나머지가 1, 1보다 클때 4로 나눈 나머지가 3인 총 4가지 케이스가 반복된다는 것을 보고 그대로 구현하려 했는데 잘 안되더군요...
> 문제 자체가 잘 이해가 안되니 풀이가 제대로 동작하지 않았던 것 같습니다..ㅠㅠ
=> [BOJ] 16918_봄버맨 / 실버1 / 120분 / X

week15/BOJ_14940/쉬운 최단거리_홍지훈.py
- 백준 14940-쉬운 최단거리
`bfs`
- 처음엔 모든 지점을 완전탐색하며 1을 만날 때마다 bfs 를 돌려 2까지 도달할 때의 거리를 갱신해주었습니다. 그러니 시간초과가 떠서 다시 2인 지점을 찾고 거기서부터 한번만 bfs 를 하며 도달가능한 1들을 거치며 bfs 인 만큼 거리를 한 계층마다 갱신할 수 있었고 도달하지 못한 지점들은 처음부터 -1로 초기화하여 문제의 조건을 만족했습니다.
=> [BOJ] 14940_쉬운 최단거리 / 실버1 / 60분 / O

week15/BOJ_2667/단지번호붙이기_이서연.py
- 백준 2667-단지번호붙이기
BFS
- 지도를 탐색하며 해당 좌표에 집이 있고, 방문하지 않았다면, 단지 번호(num)를 1 증가시키고, bfs 실행
- bfs
- 인접한 4개 방향으로 이동
- 해당 좌표에 집이 있고, 방문하지 않음 → 지도에서 해당 좌표의 값을 단지 번호(num)로 변경 & 방문 처리
- result : 단지 내 집의 개수를 저장하고 있는 리스트
- result.sort()를 통해 오름차순 정렬 후, result 출력
=> [BOJ] 2667_단지번호붙이기 / 실버1 / 45분 / O

week15/BOJ_14502/연구소_이서연.py
- 백준 14502-연구소
BFS, 백트래킹
- result : 안전 영역 크기의 최댓값
- make_wall(cnt)
- 매개변수로 세울 수 있는 벽의 개수(cnt)를 받음
- 백트래킹을 사용하여 해당 칸이 빈 칸이라면, 벽을 세움
- 3개의 벽을 모두 세웠다면, bfs()를 통해 안전 영역 탐색
- bfs
- 바이러스가 이동할 수 있는 경우, 해당 칸의 값을 0에서 2로 변경해야 하므로 deepcopy를 통해 기존 graph 복사
- queue에는 바이러스의 좌표값을 저장
- 반복문을 돌며 이동한 좌표 값이 빈 칸인 경우, 해당 값을 2로 변경
- 탐색이 끝난 후, 기존 result 값과 graph에서 0의 개수(안전 영역 수) 중, 최댓값을 result로 업데이트
=> [BOJ] 14502_연구소 / 골드4 / 45분 / X

week15/BOJ_2206/벽 부수고 이동하기_이서연.py
- 백준 2206-벽 부수고 이동하기
BFS
- visited : (0, 0)부터 해당 지점까지의 거리를 저장하고 있는 3차원 배열
- visited[x][y][0] : 벽을 부수지 않고 해당 좌표까지 이동한 거리
- visitted[x][y][1] : 벽을 부수고 해당 좌표까지 이동한 거리
- bfs
- 이동한 위치가 (N, M)일 경우, visited 배열 값 return(해당 위치까지의 거리)
- 인접한 4개 방향 이동
- 이동한 위치가 이동할 수 있는 칸이고, 방문한 적이 없음 → 이전 좌표의 visited 값 + 1로 visited 배열 업데이트
- 이동한 위치가 벽이고, 방문한 적이 없음
- 벽을 이미 부순 경우(crashed = 1) → continue
- 벽을 부수지 않은 경우 → 이전 좌표의 visited 값 + 1로 visited 배열 업데이트 (업데이트하는 visited의 3번째 인덱스 값은 1이어야 함!!)
- 탐색을 하였지만, (N, M)까지 도달하지 못한 경우, -1 return
=> [BOJ] 2206_벽 부수고 이동하기 / 골드4 / 60분 / X

week15/BOJ_1012/유기농배추_양승혜.py
- 백준 1012-유기농 배추
- BFS
- 배추가 심어져 있는 좌표가 뒤바뀌어 주어져 있다는 것을 늦게 알아 차려서 시간이 좀 걸렸습니다...^-^...
- 빈 이중배열을 0으로 가득 채우고, 주어진 위치 좌표에 1을 넣는다.
- 만약 배열의 값이 1이라면 bfs 함수를 실행시키고, 벌레의 수를 1 증가시킨다.
=> [BOJ] 1012 유기농 배추 / 실버2 / 90분 / O

week15/BOJ_14940/쉬운최단거리_양승혜.py
- 백준 14940-쉬운 최단거리
- BFS
- 주어진 조건에 따라 입력값을 담는다
- 방문한 좌표 및 답을 기록할 visited 배열을 -1로 가득 채운다
- 방문이 불가한 좌표는 -1로 기록하기 때문
- 그래프의 값이 0이면 visited의 값도 0으로 바꾼다.
- 그래프의 값이 2이면 bfs()함수를 실행시킨다.
- bfs()함수는 상, 하, 좌, 우를 돌며 좌표의 범위를 넘지 않고, 방문하지 않았고, 그래프의 값이 1이면 그 전 값의 +1 한 값을 visited 배열의 값으로 한다.
- 마지막으로 출력할 때 join을 이용하여 출력하였다.
=> [BOJ] 14940 쉬운 최단거리 / 실버1 / 80분 / O

week15/BOJ_16918/봄버맨_양승혜.py
- 백준 16918-봄버맨
- 구현
- 로직을 생각해내는 건 오래 걸리지 않았는데 'O'(알파벳)를 '0'(숫자) 으로 착각해서 오래걸렸습니다ㅠㅠㅠ 흐엉엉.... 대왕 삽질...
- 폭탄이 터지는 경우를 차례대로 그려보니 계속 반복되는 구조였습니다.
- 따라서 n이 1일때는 초기 입력상태를 출력하고
- n이 짝수일 때는 'O'으로 가득찬 격자를 출력하고
- n을 4로 나누었을 때 3이 되면(3, 7, 11, 15 ...) 'O'으로 가득찬 격자위에 폭탄이 1번 터졌을 때를 출력하고
- n을 4로 나누었을 때 1이 되면(5, 9, 13 ...) 'O'으로 가득찬 격자위에 폭탄이 1번 터진 상태에서 다시 폭탄을 터뜨린 상태를 출력합니다.
=> [BOJ] 16918 봄버맨 / 실버1 / 90분 / O

week15/BOJ_2667/단지번호붙이기_양승혜.py
- 백준 1667-단지번호붙이기
- BFS
- 입력값을 받은 graph의 좌표가 1일때 bfs()함수를 실행한다.
- 이 때 bfs()함수는 집의 개수를 return 하기에, 집의 개수를 담는 리스트에 bfs()함수의 결과값을 append 해준다.
- 단지의 개수는 집의 개수를 담는 리스트의 len과 같기에 리스트의 len을 출력하고, 집의 개수를 담은 리스트를 오름차순으로 정렬한 값을 for loop를 이용해 하나씩 차례로 프린트한다.
=> [BOJ] 2667 단지번호붙이기 / 실버1 / 25분 / O

week16/BOJ_17836/공주님을 구해라_홍지훈.py
- 백준 17836-공주님을 구해라!
`bfs`
1. 그람과 닿을 때는 그람을 얻을 경우의 거리만 갱신
2. bfs 를 통해 (N, M) 에 도달할 때 이동거리와 그람의 거리를 비교해 더 작은 값을 반환
3. 공주를 구하지 못할 때 
위의 세가지 경우가 있어 각각의 경우 걸린 시간을 bfs 를 통해 반환합니다.
이때의 시간이 T 보다 작거나 같으면 걸린 시간을 출력하고 초과할 경우 Fail 을 출력합니다.
=> [BOJ] 17836_공주님을 구해라! / 골드5 / 110분 / O

week16/BOJ_4963/섬의 개수_홍지훈.py
- 백준 4963-섬의 개수
`bfs`
- bfs 중 2차원 배열을 이용해 푸는 문제였고 기존 흔한 bfs 와 차이로는 테스트 케이스가 여러번 존재하는 것과 대각선도 이어져 있는 것으로 보는 것 외에 별다른 차이가 없는 문제입니다.
=> [BOJ] 4963_섬의 개수 / 실버2 / 20분 / O

week16/BOJ_14716/현수막_홍지훈.py
- 백준 14716-현수막
`bfs`
> 앞의 문제랑 거의 비슷한 문제였네요.. 
자동 merge 수정
/schedule
=> [BOJ] 14716_현수막 / 실버1 / 10분 / O

week16/BOJ_4963/섬의개수_양승혜.py
- 백준 4963-섬의 개수
- BFS
- 입력받은 그래프를 돌며 값이 1이면 BFS()함수를 돌도록하였다.
- 상, 하, 좌, 우, 대각선 (합하여 8방향)을 돌며 그래프의 값이 1이면 그래프의 값을 0으로 바꾸고 큐에 값을 append 한다.
- BFS()함수를 실행할 때마다 하나씩 카운트하고,
- count한 값을 즉시 프린트한다.
=> [BOJ] 4963_섬의 개수 / 실버2 / 30분 / O

week16/BOJ_14716/현수막_양승혜.py
- 백준 14716-현수막
- BFS
- 상, 하, 좌, 우, 대각선을 돌면서 값이 1이면 BFS()함수를 실행하고, 
- 함수가 실행될 때마다 카운트를 하나씩 올려준다.
=> [BOJ] 14716_현수막 / 실버1 / 15분 / O

week16/BOJ_17836/공주님을구해라_양승혜.py
- 백준 17836-공주님을 구해라!
- BFS
BFS함수 내에 
1. 공주가 있는 곳에 도달했을 때 -> 검을 발견했을 때의 거리와 현재 거리를 비교하여 더 짧은 거리를 반출
2. 검을 발견했을 때 -> 검을 발견했을 때의 거리를 갱신
3. 0일 때 -> 조건에 맞으면 1씩 거리를 추가
위의 조건들을 구분하여 코드를 구현하고,
최소 거리를 return 한다.
문제에서 주어진 저주 시간보다 길면 Fail, 짧으면 해당 시간을 프린트한다.
=> [BOJ] 17836_공주님을 구해라! / 골드5 / 115분 / X

week17/BOJ_2217/로프_홍지훈.py
`그리디 알고리즘`
- 위의 참고자료처럼 1개 ~ N 개까지 고를 수 있습니다.
- 최대 무게는 i 개를 골랐을때 그 i 개중 가장 가벼운 무게 * i 를 한 것과 같습니다.
- 그러므로 그리디 알고리즘을 적용했을 때 1 개에서 ~ N 개까지 고를 수 있을 때 각각의 경우에서 전체 로프들의 무게중 무거운 것부터 순서대로 i 번째 값 * i 를 한 값이 max 값과 비교했을 때 더 커지면 답을 갱신합니다.
그리디 알고리즘 적용시 어떤 관점에서 접근하셨을지 궁금하네요
저는 로프들을 weight 라는 배열에 담아 오름차순으로 정렬시키고 로프를 고르는 수에 따라 가장 무거운 것부터 i 번째의 로프 무게 * 고른 로프들의 수와 기존 max 무게를 비교해서 조건을 만족할 때만 갱신하는 식으로 접근했어요
=> 실버3 / 30분 / O

week17/BOJ_11000/강의실 배정_홍지훈.py
`그리디 알고리즘`
강의시작 시간을 기준으로 오름차순 정렬합니다.
우선순위 큐를 사용하여 가장 우선순위가 높은 ( 가장 빨리 끝나는 강의실 ) 강의실의 끝나는 시간보다 새로 시작하는 강의의 시작시간이 크거나 같을 경우 강의실을 새로 추가하지 않고 이어서 사용가능하며 그 외의 경우엔 강의실을 추가합니다.
방법을 찾지 못한건데 강의가 끝나는 시간 기준으로 정렬해서 풀수는 없을까요..?
=> 골드5 / 40분 / O

week17/BOJ_2217/로프_홍지훈.py
`그리디 알고리즘`
- 그리디 알고리즘을 적용하기 위해 가장 탐욕적으로 비교해야 할 대상으로 각 도시별 다음 도시까지 계산할 최소 리터당 금액을 선정했습니다.
- 그래서 한 도시에서 무제한으로 기름을 살 수 있으니 각 도시를 지나며 최소 금액으로 얼만큼 사야하는지를 비교하여 전체 금액을 계산하는 방식으로 코드를 구성했습니다.
그리디 알고리즘으로 어떤 것을 기준으로 코드를 구성하셨나요?
=> 실버3 / 5분 / O

week17/BOJ_1455/뒤집기 II_홍지훈.py
`그리디 알고리즘`
오른쪽 아래서부터 반대로 왼쪽 위로 올라가며 뒷면인 동전이 있으면 조건을 만족하는 동전들을 모두 뒤집는 것을 반복합니다.
제 풀이가 그리디같으면서도 완전탐색과 큰 차이가 없는 것 같아 리뷰어님의 코드를 참고해보겠습니다...
=> 실버1 / 20분 / O

week17/BOJ_1455/뒤집기 II_이서연.py
그리디
- 가장 오른쪽 아래부터 왼쪽 위까지 탐색하며 카드가 뒷면이면, 횟수 증가시키고 flip() 을 통해 (0, 0)부터 현재 위치까지 전체 카드 뒤집기
=> 실버1 / 40분 / X

week17/BOJ_2141/우체국_이서연.py
그리디
- 마을 번호를 기준으로 villages 배열을 오름차순 정렬
- 마을들 전체 인원 수 합의 절반이 넘어가는 순간이 인원 수의 중앙값이므로 해당 위치에서 마을 번호 출력
=> 골드4 / 30분 / X

week17/BOJ_2217/로프_이서연.py
그리디
- 로프를 최대 중량에 대해 내림차순으로 정렬
- 반복문을 통해 로프 배열을 돌며 이전까지의 최대 중량(result)과 새로운 로프를 통해 들 수 있는 중량(i * cnt) 을 비교하여 더 큰 값으로 result 업데이트
=> 실버4 / 10분 / O

week17/BOJ_8980/택배_이서연.py
그리디
- 도착지가 빠른 순으로 정렬
- available에는 인덱스번째 마을부터 그 다음 인덱스번 마을까지 이동할 택배의 무게를 저장
- 반복문을 돌며 트럭에 실을 수 있는 무게를 찾은 후, available 배열에 해당 무게를 더해 update
- result에 해당 무게를 더함
=> 골드2 / 100분 / X

week17/BOJ_11000/강의실 배정_이서연.py
그리디
- 최소값이 맨 앞으로 오도록 유지하기 위해 heapq 사용
- 강의가 시작하는 순서대로 정렬
- 반복문을 돌며 heap(현재 강의실)의 0번째 값(해당 강의실에서 가장 늦게 끝나는 수업의 시간)과 현재 강의 시작 시간을 비교
- 강의 끝나는 시간이 현재 강의 시작 시간보다 늦다면, 새로운 강의실 개설(push)
- 강의 끝나는 시간이 현재 강의 시작 시간보다 빠르다면, 해당 강의실에 추가(pop한 후, push)
=> 골드5 / 70분 / X

week17/BOJ_13305/주유소_이서연.py
그리디
- 해당 주유소의 가격이 현재 가격보다 작으면, 현재 가격을 update
- result에 비용(현재 가격 * 이동 거리) 추가
=> 실버3 / 30분 / X

week17/BOJ_2217/로프_최재선.js
- 백준 2217-로프
- 그리디
- 로프를 중량 오름차순 정렬
- 각 로프의 무게로 병렬 처리했을 때 값과 max값을 비교 업데이트
=> 실버4 / 5분 / O

week17/BOJ_13305/주유소_최재선.js
- 백준 13305-주유소
- 그리디
- 범위 BigInt 처리
- 들렸던 주유소 중 가장 유가가 낮은 주유소 가격으로 구매
=> 실버3 / 10분 / O

week17/BOJ_1455/뒤집기 II_최재선.js
- 백준 11000-강의실 배정
- 좌표 압축
- 정렬
- x축 기준 오름차순 정렬 후, 양쪽 사람 수가 균일하게 되는 곳을 return
=> 실버1 / 10분 / O

week16/BOJ_10711/모래성_최재선.js
- 백준 10711-모래성
- bfs
- 파도가 칠 때 마다, 무너진 벽이 있는지 체크
- 벽이 무너진 곳을 queue에 담은 다음, 무너진 벽의 8방향의 벽에 대해 -1 계산
- 벽이 다 무너져 0이 된다면, queue에 push
- 새로운 queue로 교체
- queue의 length가 0이 된다면 break
=> [BOJ] 10711 모래성 / 골드2 / 10분 / O

week17/BOJ_2141/우체국_최재선.js
- 백준 2141-우체국
- 정렬
- x축 기준 오름차순 정렬 후, 양쪽 사람 수가 균일하게 되는 곳을 return
=> 골드4 / 40분 / O

week17/BOJ_11000/강의실 배정_최재선.js
- 백준 11000-강의실 배정
- 좌표 압축
- 정렬
- x축 기준 오름차순 정렬 후, 양쪽 사람 수가 균일하게 되는 곳을 return
=> 골드 5 / 10분 / O

week17/BOJ_8980/택배_최재선.js
- 백준 8980-택배
- Lazy SegmentTree
- Greedy
- 정보를 도착지 기준으로 오름차순 정렬, 같다면 출발지 오름차순
- 순회하며, 해당 출발지 도착지 사이에 쌓인(acc) 배송 수의 max값을 구한 뒤, 현재 최대로 배송 가능한 박스 수 계산
- 해당 박스 수 만큼 결과값에 더하고 해당 range(start, end)에 박스 수 더하여 업데이트
=> [BOJ] 8980 택배 / 골드1 / 70분 / O

week16/BOJ_17836/공주님을 구해라!_최재선.js
- 백준 10711-공주님을 구해라!
- bfs
- bfs 탐색하면서, 칼을 구하면 공주까지의 최단거리로 flag 저장
- bfs 탐색지점의 끝에 도달하거나, 현재 시각이 칼로 최단거리에 갔을 때의 시간보다 커진다면 break
=> [BOJ] 10711 공주님을 구해라! / 골드5 / 35분 / O

week17/BOJ_13305/주유소_양승혜.py
- 그리디
- 입력값을 거리, 비용에 따라 따로 리스트에 담아서 보관한다
- 비용의 0번째 인덱스를 타겟으로 놓고,
- n-1번만큼 for문을 돌면서 현재 타겟으로 잡아놓은 비용보다 비용이 적으면 (비용 * 거리)를 한 값을 answer 변수에 더한다
=> 실버3 / 25분 / O

week17/BOJ_1455/뒤집기 II_양승혜.py
- 그리디
- 동전을 오른쪽 > 왼쪽, 아래 > 위 순으로 뒤집으면서 답을 도출한다.
- 동전을 앞에서부터 차례로 뒤집으면 나중에 오른쪽, 아래 동전을 뒤집을 때 영향을 많이 받아 선택했던 동전을 또다시 선택해야하는 일이 발생하기 때문이다.
- 'flip()'이라는 함수를 따로 만들어서 동전을 차례로 뒤집는 함수를 따로 구현해주었다.
=> 실버1 / 40분 / O

week17/BOJ_11000/강의실 배정_양승혜.py
- 우선순위 큐, 그리디
<사설😂>
- 하하... 이거 처음에 그냥 단순히 리스트로 풀다가 시간초과 나고 예외케이스들도 많이 발생해서 뭐지 싶었는데 우선순위 큐를 이용해야했습니다..!
- 그리고 파이썬으로 풀면 우선순위큐로 풀어도 시간초과 납니다..!
- `import sys`를 잘 안하려고하는데 이번엔 sys를 import해야 시간초과 안 나고 통과되더라고요...^-^.....
<설명>
- 강의가 시작되는 시간을 기준으로 input값을 정렬한다
- 힙에는 끝나는 시간을 둔다
- input으로 받은 값들을 돌면서 수업 시작 시간이 heap의 첫 값(가장 작은 값)보다 작거나 같으면 `heappop()`을 통해 heap()의 가장 첫 번째 값을 지운다.
- 그리고 heap에 수업이 끝나는 시간을 저장한다.
- 끝까지 반복하고 heap에 남아있는 원소의 개수를 구한다.
- 혹시 `import sys` 하지 않고 푸신분 계신가요... 어떤 방법으로 풀면 `import sys`안 하고 input만 받아도 통과될만큼 빨라질까요..?
=> 골드5 / 60분 / O

week17/BOJ_2141/우체국_양승혜.py
- 누적합, 그리디
<사설>
- 처음엔 각각의 사람마다 비용이 얼마나 들었는지를 일일히 계산해서 가장 적은 값을 가지는 도시에 우체국을 세우는 식으로 문제를 풀었는데 당연히 시간초과가 났습니다...^-^...
- 처음에 막연히 '그냥 인구 수 반 넘어가기 시작하면 답아니야~~??'하고 장난으로 생각했는데 너무 문제 단순히 생각한 것같아서 당연히 답이 아닐줄 알았거든요..? 근데 이게 맞더라고요..??(당황)
<풀이>
- 입력을 받을 때 총 인구의 수를 구하고, 입력값을 리스트에 저장합니다. 
- 도시의 순번대로 sort()를 합니다.
- 저장된 입력값을 for문으로 돌면서 인구수의 누적합을 차례대로 구하는데, 이 누적합이 (총 인구수의 / 2)가 넘어가는 시점을 답으로 도출합니다.
- 이게 무슨 연유에서 이렇게 되나 저도 찾아봤는데, 귀류법으로 증명하는 수밖에 없다고 생각합니다.
- 예를 들어, 인구수의 / 2인 지점이 i라고했을 때, i - 1, i + 1인 지점보다 i가 더 효율적인 것이죠...! 이런식으로 모든 지점의 효율성을 구했을 때 총인구수의 / 2가 넘어가기 시작하는 시점부터가 최적의 답이 되는것이죠.
- 그리디 알고리즘의 귀류법에 대해 설명해놓은 글을 공유합니다!
- [Algorithm Analysis - Greedy Algorithm1](https://hyunw.kim/blog/2018/09/18/Algorithm_Analysis07_GreedyAlgorithm1.html)
- 아 그리고 (총 인구수 // 2)를 기준으로 두면 틀립니다!! 
- 부끄럽지만 시간초과 난 첫번째 코드도 공유합니다 …
=> 골드4 / 45분 / O

week18/BOJ_15990/1, 2, 3 더하기 5_홍지훈.py
`dp`
저는 memo 라는 딕셔너리에 가능한 경우중 1로 끝나는 경우, 2로 끝나는 경우, 3으로 끝나는 경우의 수를 배열의 값으로 담는다는 생각을 하며 풀이를 했습니다.
이럴 경우 n번째 memo 는 memo[n-3] 에서 1로 끝나는 경우, 2로 끝나는 경우에 3을 더하면 되고 
memo[n-2] 에서 1로 끝나는 경우, 3로 끝나는 경우에 2을 더하면 되고 
memo[n-1] 에서 2로 끝나는 경우, 3로 끝나는 경우에 1을 더하면 된다고 생각해서 점화식을 구성했습니다.
점화식 접근의 차이가 있다면 남겨주시면 좋을 것 같아요 ㅎㅎ
=> 1,2,3 더하기 5 / 실버2 / 40분 / O

week18/BOJ_11052/카드 구매하기_홍지훈.py
`dp`
- 카드팩은 1 ~ N 개까지 포함되어 있을 수 있으니 dp 를 비교하는 기준은 기존 값과 1 ~ i 까지 값 + prices[i] 중 최대값으로 갱신한다는 생각을 갖고 최대 지출액을 구하는 식으로 코드를 구성했습니다.
- dp 인데 완전탐색 같은 느낌으로 코드를 짜서 이게 맞나 싶네요..? ㅎㅎ;;
=> 카드 구매하기 / 실버1 / 50분 / O

week18/BOJ_12872/플레이리스트_최재선.js
- dp
- 수학
1. 안 뽑힌 사람을 고려하지 않고 뽑는 방법의 경우의 수 (함수 f로 정의)
- (n <= m) 인 경우
- n = p 이라면 n!
- 그게 아니라면 0
- (n > m) 인 경우
- f(n) = (n! / (n - m)!) * (n - m) ^ (p - m)
2. 안 뽑힌 사람도 없도록 고려하여 dp를 계산
- dp(n) = f(n) - (Σ(k) from 1 to n-1 >> C(n, k) * dp(k))
=> 플레이리스트 / 골드 1 / 40분 / O

week18/BOJ_11066/파일 합치기_최재선.js
- dp
- 재귀
- (left, right) 범위에서의 최소 계산값을 구하는 재귀 함수를 구현
- (left, right) 가 같을 시 return 0 (단일)
- (left, right) 가 1 차이가 날 시, sum을 return
- 그 외의 경우, 해당 범위의 부분 합과 해당 범위를 쪼개서 재귀 함수를 실행
- 만약 1 ~ n 인 경우 {(1, 2), (3, n)}, {(1, 3), (4, n)} ... 등 과 같이 재귀함수를 실행 후, 최소 값을 결과에 더함
- merge sort + binary search 방식을 사용해서 할 수 없을까요?
해당 방식으로 구현 시 문제점
1. input 값으로 21 14 17 32 이 오면, 14, 17을 먼저 더하는 것이 최소 값이 도출되는데, 21, 14를 먼저 더해서 오차값 1이 발생
```js
const fs = require('fs');
const inputs = fs.readFileSync(process.env.LOGNAME === 'jake' ? './input.txt' : '/dev/stdin')
.toString().trim().split('\n');
const args = [];
for (let i = 1; i < inputs.length; i += 2) {
args.push(inputs[i + 1].split(' ').map(Number));
}
const binarySearch = (arr, value) => {
let left = 0;
let right = arr.length;
let result = -1;
while (left <= …
```
=> 파일 합치기 / 골드 3 / 100분 / O

week18/BOJ_11052/카드 구매하기_최재선.js
- 백준 11052
- dp
- dp[i] = max(dp[i - 1] + dp[0], dp[i - 2] + dp[1] ...);
=> 카드 구매하기 / 실버1 / 15분 / O

week18/BOJ_15990/1, 2, 3 더하기 5_최재선.js
- 백준 15990
- dp
- 1, 2, 3 각각으로 끝나는 것 기준 dp 배열 생성
=> 1, 2, 3 더하기5 / 실버2 / 15분 / O

week18/BOJ_15990/1, 2, 3, 더하기 5_양승혜.py
- dp
- 도무지 점화식이 떠오르지 않아서 풀이를 보고 힌트를 얻은다음에 풀었습니다..!
- 경우의 수 중 1, 2, 3으로 끝나는 경우를 [0, 0, 0] 리스트에 넣어 보관합니다.
- 예를 들면, 1은 [1, 0, 0], 2는 [0, 1, 0], 3은 [1, 1, 1]이 됩니다.
- 4부터 계산을 해보자면
- n - 1번째 경우에서 1로 끝나는 경우는 경우의 수에 산입하면 안 됩니다. 따라서 [n - 1][1], [n - 1][2]의 값을 [n][0]에 넣습니다.
- n - 2, n - 3번째 경우도 n - 1의 경우와 같이 처리합니다.
- 해당 dp배열의 리스트 안에 있는 값의 sum에 10 ** 9 + 9한 값을 mod연산하여 리턴합니다.
- 점화식을 떠올리지 못해 보고 풀어서 X표 쳤습니다
- 이해 완료하고 풀었습니다! 힌트를 보고풀었는데 이게 너무 메인 힌트라... 헤헤....
=> 1, 2, 3 더하기5 / 실버2 / 70분 / X

week18/BOJ_11052/카드 구매하기_양승혜.py
- dp
- 점화식이 잘 안 세워져서 힌트를 보고 풀었습니다!
- 핵심 점화식은 아래와 같습니다.
- dp[i]는 dp[i - j] + 비용[j]한 값을 max로 계속 갱신한 값입니다.
```python
for i in range(1, n + 1):
for j in range(1, i + 1):
dp[i] = max(dp[i], dp[i - j] + costs[j])
```
- 힌트를 보고 풀었고, 이해했습니다!
=> 카드 구매하기 / 실버1 / 75분 / X

week18/BOJ_2225/합분해_양승혜.py
- dp
- k가 1일때부터 3일때까지 쭉 써내려가다보니 표의 숫자들에 규칙이 있었습니다.
|K\N|1|2|3|4|
|:---:|:---:|:---:|:---:|:---:|
|1|1|1|1|1|
|2|2|3|4|5|
|3|3|6|10|15|
- dp[i][j] 는 (위의 숫자 + 왼쪽의 숫자)였습니다.
따라서
```dp[i][j] = (dp[i - 1][j] + dp[i][j - 1]) % 1000000000```
라는 점화식이 나왔습니다.
=> 합분해 / 골드5 / 70분 / O

week19/BOJ_3019/테트리스_홍지훈.py
`구현`
결국 블럭 타입별 높이 차이에 의해 카운트를 하는 것으로 보여서 타입별 카운트하는 유형별로 정리를 했고
한번 n 번만큼 순회하며 각 유형이 몇개씩 존재하는지를 구해
블럭별 가능한 수를 구하는 식으로 구현했습니다.
```py
'''
각 블럭별로 정면, 90, 180, 270 4가지 종류의 타입을 갖고
1 ~ C 까지 움직일 수 있다.
각 블럭 타입별로 올 수 있는 유형을 정리해야 한다.
1번 블럭)
모든칸 / 4칸 연속 같은 높이
2번 블럭)
2칸 연속 같은 높이
3번 블럭)
3칸 오른쪽 칸이 한칸 높게 / 2칸 왼쪽 칸이 한칸 높게
4번 블럭)
3칸 왼쪽 칸이 한칸 높게 / 2칸 오른쪽 칸이 한칸 높게
5번 블럭)
3칸 연속 같은 높이 / 2칸 오른쪽 칸이 한칸 높게 / 3칸 양 옆이 한칸 높게 / 2칸 왼쪽 칸이 한칸 높게
6번 블럭)
3칸 연속 같은 높이 / 2칸 연속 같은 높이 / 3칸 왼쪽 칸이 한칸 낮게 / 2칸 왼쪽 칸이 두칸 높게
7번 블럭)
3칸 연속 같은 높이 / 2칸 연속 같은 높이 / 2칸 오른쪽 칸이 두칸 높게 / 3칸 오른쪽 칸이 한칸 낮게
=> 유형을 나눠보자 types = [a0, a1, a2, a3, b0, b1, b2, b3, b4, c0, c1]
0 모든칸 C
1 4칸 연속 같은 높이
2 3칸 연속 같은 높이
3 2칸 연속 같은 높이
4 3칸 오른쪽 한칸 높
5 3칸 왼쪽 한칸 높
6 3칸 오른쪽 한칸 낮
7 3칸 왼쪽 한칸 낮
8 3칸 양옆 한칸 높
9 2칸 왼쪽 한칸 높
10 2칸 오른쪽 한칸 높
11 2칸 왼쪽 두칸 높
12 2칸 오른쪽 칸 두칸 높
''' …
```
=> 테트리스 / 실버1 / 30분 / O

week19/PSG_괄호 변환/괄호 변환_홍지훈.py
`구현`
앞에서부터 순서대로 요구사항을 만족하는 코드를 구성합니다...
> 시간을 넘겨서 다른 분들의 코드를 참고했습니다,, 어렵네요ㅠㅜ
x
=> 괄호 변환 / lv.2 / 120분 / X

week19/BOJ_16937/두 스티커_홍지훈.py
`구현`
- 스티커 2개를 선정
- 각 스티커를 가로로 이어서, 세로로 이어서, 가로, 세로 쌍의 경우 최대 영역의 넓이를 갱신
=> 두 스티커 / 실버3 / 40분 / O

week19/BOJ_16937/두 스티커_양승혜.py
- 구현
- 그리디하게 풀어보려다가 결국엔 전부 탐색을 해야한다는 것을 깨닫고 그냥 구현으로 풀었습니다..!!
- 처음엔 스티커의 정보를 받아서 스티커의 넓이가 큰 순서대로 정렬한다음에 탐색을 하면 더 효율적으로 풀수있을까 싶었는데 그냥 어차피 회전하는 경우의 수까지 구해서 코드를 짜야하더라고요...!
- 스티커의 정보를 받을 때 너비, 높이 조건에 어긋나는 스티커일 경우 스티커 리스트에 정보를 저장하지 않습니다.
- 스티커의 가로, 세로길이가 그대로일때, 첫 번째 스티커만 회전할 때, 두 번째 스티커만 회전할 때, 두 스티커가 모두 회전했을 때의 조건 네 개를 분기해서 max값을 갱신하도록 했습니다.
- 혹시 더 효율적으로 푸신분 계신가요?
=> 두 스티커 / 실버3 / 50분 / O

week19/BOJ_16938/캠프 준비_양승혜.py
- 조합, 구현
- 가능한 문제 조합을 combinations로 구하고, 
- 문제 조건을 따지면서 조건에 맞으면 count를 하나씩 올려줍니다.
- count를 프린트합니다.
- 비트마스킹으로도 풀이 준비중입니다ㅋㅋㅋ 연구 끝나면 다시 커밋할게요~!!
=> 캠프 준비 / 골드5 / 15분 / O

week21/BOJ_16956/늑대와 양_이서연.py
- BFS
- 초기에 늑대와 양이 인접해있다면, 0을 출력
- 이 외에 존재하는 빈칸에는 모두 울타리를 설치
=> 늑대와 양 / 실버3 / 30분 / O

week21/BOJ_17086/아기 상어 2_이서연.py
- BFS
- 초기 코드 : 상어가 있는 좌표마다 bfs 탐색 후, 탐색할 때마다 안전거리 값을 distances 배열에 삽입
- 최종 결과로는 distances 배열의 최대값 출력
- 수정 코드 : 상어가 있는 좌표를 queue에 먼저 저장 후, 상어가 있는 곳부터 순차적으로 bfs 탐색
- bfs 탐색을 하며 graph 배열을 업데이트하여 안전거리 업데이트
- 최종 결과로는 graph 배열의 최대값 출력
=> 아기 상어 2 / 실버2 / 60분 / X

week21/BOJ_5014/스타트링크_이서연.py
- BFS
- 현재 지점(x)이 목표 지점(G)라면, bfs 탐색 종료
- 현재 지점(x)이 목표 지점(G)보다 낮음
- 현재 지점(x) + U가 건물 전체 층수(F)보다 작다면, U 클릭
- 현재 지점(x) + U가 건물 전체 층수(F)보다 크다면, D 클릭
- 현재 지점(x)이 목표 지점(G)보다 높음
- 현재 지점(x) - D가 1보다 크다면, D 클릭
- 현재 지점(x) - D가 1보다 작다면, U 클릭
=> 스타트링크 / 실버1 / 100분 / O

week21/BOJ_2251/물통_이서연.py
- BFS
- C에 같은 양의 물이 채워지는 것을 방지하기 위해 A, B에 담긴 물의 양을 x, y 좌표로 변환하여 visited 배열 업데이트
- A에 담긴 물의 양이 0이라면, answer 배열에 C에 담긴 물의 양 추가
- 물을 옮길 수 있는 경우의 수는 6가지 (A → B, A → C, B → A, B → C, C → A, C → B)
- 하나의 (A에 담긴 물의 양, B에 담긴 물의 양) 조합에 대해 6가지 물 옮기기 모두 진행
=> 물통 / 골드5 / 120분 / X

week21/BOJ_17141/연구소 2_이서연.py
- BFS
- combinations를 활용하여 바이러스를 놓을 수 있는 좌표의 조합을 구하고, 이에 대해 bfs 탐색
- bfs 탐색 종료 후, 벽의 개수와 visited 배열의 -1 개수가 같으면, 이는 모든 칸에 대해 바이러스가 퍼진 것이므로 visited 배열의 최대값(초수) 반환
- 개수가 같지 않다면, 이는 바이러스 퍼뜨리기를 실패한 것이므로 sys.maxsize 반환
- 기존 answer 값과 새롭게 bfs를 탐색한 결과값 중, 더 작은 값으로 answer 업데이트
=> 연구소2 / 골드4 / 100분 / X

week21/BOJ_17142/연구소 3_이서연.py
- BFS
- 비활성 바이러스가 있는 칸은 바이러스가 퍼져도, 퍼지지 않아도 모두 가능
- 따라서 하나의 좌표에 대해 bfs 탐색을 2번 실시
1. 비활성 바이러스가 있는 칸은 제외하고, 빈 칸에만 바이러스 퍼뜨리기
2. 빈 칸 + 비활성 바이러스 칸 모두 퍼뜨리기
- 1번의 경우, 빈 칸과 모든 바이러스 칸의 개수의 합이 visited1 배열의 -1칸과 0칸의 개수 합과 같으면, 모든 칸에 바이러스가 퍼진 것이므로 temp1을 visited1 배열의 최대값(초수)으로 업데이트
- 합이 다르면, temp1에 sys.maxsize 할당
- 2번의 경우, 벽의 개수와 visited2 배열의 -1칸의 개수가 같으면, 모든 칸에 바이러스가 퍼진 것이므로 temp2를 visited2 배열의 최대값(초수)으로 업데이트
- 개수가 다르면, temp2에 sys.maxsize 할당
- 1번보다 2번이 더 많은 칸을 탐색함 
- 따라서 1번 탐색을 통해 모든 칸에 바이러스가 퍼졌다면, 이는 2번 탐색보다 더 적은 시간 소요
- 1번을 통해 탐색에 성공했다면, temp1 반환
- 1번을 통해 탐색에 실패하고, 2번을 통해 성공했다면, temp2 반환
- 1번과 2번 모두 탐색에 실패했다면, sys.maxsize 반환
=> 연구소3 / 골드3 / 100분 / X

scripts/create.sh, week22/BOJ_1389/케빈 베이컨의 6단계 법칙_홍지훈.py
`다익스트라`
플로이드-워셜보다 보통 그냥 다익스트라 쓰는게 시간이 더 빠르게 나왔던 것 같아서 다익스트라로 풀었습니다.
각 유저의 관계에 대한 정보를 담는 리스트가 필요하며, 각 유저사이에 모를 경우 초기값으로 `거리: 무한대` 를 설정합니다.
최단 거리는 각 노드에서 `최단 거리가 가장 짧은 노드` 를 선택해야 합니다.
이 과정을 우선순위 큐를 이용해 구합니다.
각 노드에서 갈 수 있는 노드들을 차례로 방문해 원래 해당 노드까지의 거리와 업데이트될 거리를 비교해 최단 거리를 갱신합니다.
=> 케빈 베이컨의 6단계 법칙 / 실버1 / 20분 / O

week22/BOJ_17396/백도어_홍지훈.py
`다익스트라`
보통 무한대를 `1e9` 로 두고 푸는데 이 문제는 경우가 좀더 많았나봐요 `1e10 + 1` 이상을 무한대로 설정해야 풀린다는 글을 보고 수정했습니다
거리 = 시간으로 보니 말만 바뀐 거라 거리를 1이 아닌 걸린 시간 t 만큼 더하는 식으로 코드를 짰습니다.
다만, 최종 넥서스 외에 시야에 닿는 곳만 갈 수 없으니 그런 경우만 continue 하도록 했습니다.
=> 백도어 / 골드5 / 40분 / O

week22/BOJ_1389/케빈 베이컨의 6단계 법칙_이서연.py
- bfs
- 양방향 그래프이므로 2차원 배열(graph) 활용
- visited 배열에는 케빈 베이컨의 수 저장
- visited[0] = -1(초기값)이므로 bfs 함수에서 결과값을 return할 때, +1
=> 케빈 베이컨의 6단계 법칙 / 실버1 / 30분 / O

week22/BOJ_15723/n단 논법_이서연.py
- 플로이드-워셜
- 전제에 대해 graph[i][j] = 1로 업데이트
- 3중 반복문을 돌며, 모든 정점에 대해 탐색
- graph[i][j] = INF면 탐색하지 못한 것이므로 F, 그 외에는 T 출력
=> n단 논법 / 실버1 / 60분 / X

week22/BOJ_1916/최소비용 구하기_이서연.py
- 다익스트라
- graph에 (도착 지점, 비용) 저장
- dijkstra 함수를 실행하여 시작 지점부터 탐색하면서 distance 배열에 특정 지점까지의 최소 비용 업데이트
- distance[도착 지점] 출력
=> 최소비용 구하기 / 골드5 / 60분 / X

week22/BOJ_17396/백도어_이서연.py
- 다익스트라
- seen : 상대에게 보이는 분기점
- graph에 탐색 가능한 분기점을 저장할 때, 출발 지점과 도착 지점이 모두 상대에게 보이지 않는 경우만 append
- seen의 값이 1인 노드는 탐색 X (도착 지점은 탐색해야 하므로 seen[-1] = 0으로 변경)
- dijkstra 함수를 실행하며 상대 넥서스까지의 최소 거리인 distance 배열 업데이트
=> 백도어 / 골드5 / 30분 / X

week22/BOJ_5972/택배 배송_이서연.py
- 다익스트라
- 양방향이므로 2차원 배열(graph) 사용
- dijkstra 함수를 실행하여 출발 지점부터 도착 지점까지의 최소 비용을 저장한 distance 배열 업데이트
=> 택배 배송 / 골드5 / 20분 / O

week22/BOJ_11404/플로이드_이서연.py
- 다익스트라
- 모든 도시를 출발점으로 하여 dijkstra 함수 실행
- 해당 도시를 기준으로 다른 도시까지의 최소 비용을 저장한 temp 배열을 dijkstra의 결과값으로 반환
- 모든 도시에 대한 최소 비용을 distance 배열에 저장
=> 플로이드 / 골드4 / 40분 / O

week22/케빈 베이컨의 6단계 법칙_양승혜.py
1. 플로이드-워셜
2. bfs
플로이드-워셜, bfs 두 가지 방법 각각으로 풀어보았습니다~!
=> 케빈 베이컨의 6단계 법칙 / 실버1 / 45분 / O

week22/BOJ_11404/플로이드_양승혜.py
- 플로이드 - 워셜
- 플로이드-워셜 알고리즘을 사용하는 기본적인 문제였던 것 같습니다
- 플로이드-워셜 알고리즘을 사용하여 풀었습니다
=> 플로이드 / 골드4 / 25분 / O

week22/BOJ_1916/최소비용 구하기_양승혜.py
- 다익스트라
- 다익스트라를 이용한 기본적인 문제였습니다.
- 다익스트라를 이용해서 최소 거리를 구하고, 도착 도시에 해당하는 값을 꺼내왔습니다.
=> 최소비용 구하기 / 골드5 / 80분 / X

week23/BOJ_17070/파이프 옮기기 1_홍지훈.py
=> 파이프 옮기기 1 / 골드5 / 60분 / X

week23/BOJ_17626/Four Squares_홍지훈.py
`dp`
제곱근이 정수인지 아닌지를 나타내는 sq 배열을 생성합니다
최대 4개까지의 자연수 제곱수의 합으로 나타낼 수 있다고 했으니 결과는 1 ~ 4 가 됩니다.
1. 수 1개일 때 - 만약 입력한 수가 sq 에서 1 이라면 ( 제곱근이 정수 ) 바로 1을 반환 ( 1, 4, 9, 16, ... )
2. 수 2개일 때 - 만약 입력한 수 - 제곱근이 정수라면 2를 반환 ( 1 + 25, 3 + 16 ... )
3. 수 3개일 때 - 만약 입려한 수 - 제급근 - 제곱근이 정수라면 3을 반환 ( 1 + 4 + 9, ... )
=> Four Squares / 실버3 / 40분 / X

week23/숫자 재배치_양승혜.py
- 완전탐색
- 각 조건들의 분기마다 if와 else를 사용해서 문제 풀이
- 순열은 itertools를 사용했음
- 비트마스킹으로 itertools를 대체해보고싶은데 잘 안 되네요😂
=> 숫자 재배치 / 실버1 / 25분 / O

week24/BOJ_17626/Four Squares_이서연.py
- 완전탐색
- is_square 배열의 인덱스가 제곱수인 경우만 True로 저장
- 입력 받은 n이 제곱수인 경우, 1 출력
- n - (i * i)가 제곱수인 경우, 2 출력
- n - (i * i) - (j * j)가 제곱수인 경우, 3 출력
- 이외의 경우에는 4 출력
=> Four Squares / 실버3 / 30분 / X

week24/BOJ_14620/꽃길_이서연.py
- 완전탐색
- computations를 통해 씨앗을 심을 수 있는 3개 좌표의 조합을 구함
- 모든 조합에 대해 calculate 함수 실행
- 꽃을 심을 수 있다면, temp에 땅을 대여하는 비용을 더하고, 꽃을 심었음을 나타내기 위해 visited 배열의 값을 True로 변경
- 모든 조합에 대해 씨앗을 심은 후, temp 값(땅의 대여비)과 result 중, 더 작은 값으로 result 업데이트
=> 꽃길 / 실버2 / 30분 / X

week24/BOJ_16943/숫자 재배치_이서연.py
- 완전탐색
- A를 문자 배열로 만들고, permutations를 통해 해당 숫자로 만들 수 있는 모든 순열을 구함
- 0으로 시작하는(가장 왼쪽이 0) 숫자가 아니고, 만들어진 숫자가 B보다 작다면, 기존의 C 값과 만들어진 값 중, 더 큰 것으로 C 업데이트
- C가 0(초기값)이면, -1 출력
- 그 외에는 C 출력
=> 숫자 재배치 / 실버1 / 30분 / O

week24/BOJ_15686/치킨 배달_이서연.py
- 완전탐색
- 가능한 치킨집의 개수는 최대 M개이므로 0부터 M까지 for문을 돌며, 치킨집이 위치할 수 있는 좌표값의 조합을 구함
- hx, hy : 집의 좌표값
- 특정 집부터 모든 치킨집의 좌표값에 대해 치킨 거리를 구한 후, 가장 최소값으로 temp 업데이트
- 해당 집의 치킨 거리를 chicken_distance 배열에 append
- 모든 집의 치킨 거리를 구하는 과정이 끝나면, chicken_distance 배열의 합과 result를 비교하여 최소값으로 result 업데이트
- result 출력
=> 치킨 배달 / 골드5 / 25분 / O

week24/BOJ_15886/내 선물을 받아줘 2_이서연.py
- 구현
- E와 W가 연속으로 있는 경우, W 바로 앞에 있는 E에 선물을 두어야 하므로 해당 조건에 해당하는 E의 개수 count
=> 내 선물을 받아줘 2 / 실버3 / 20분 / O

week24/BOJ_16945/매직 스퀘어로 변경하기_이서연.py
- 완전 탐색
- 순열 라이브러리를 활용해 1부터 9까지의 수로 만들 수 있는 모든 스퀘어 생성
- 생성된 스퀘어에 대해 is_square()를 통해 해당 스퀘어가 매직 스퀘어인지 확인
- 매직 스퀘어라면, 모든 칸을 방문하며 비용 계산
- 비용의 최소값으로 result 업데이트
=> 매직 스퀘어로 변경하기 / 실버2 / 40분 / X

week24/BOJ_16987/계란으로 계란치기_이서연.py
- 백트래킹
- 오른쪽에 더 이상 들 계란이 없는 경우(n == N), return
- 현재 들고 있는 계란이 깨져있는 경우(graph[n][0] <= 0), 다음 단계로 이동
- 부딪히려고 하는 계란이 자기 자신(n == i)이거나 이미 깨진 경우(graph[i][0] <= 0), continue
- 계란을 부딪힌 경우, 각 계란의 내구도 업데이트
- 계란을 깬 개수(cnt)를 변경한 후, 다음 단계로 이동
- backtracking 호출이 끝나면, 원상복귀
- 아무 계란과도 부딪히지 않았다면(flag == False), 다음 단계로 이동
=> 계란으로 계란치기 / 골드5 / 100분 / X
